
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  VIEWER: 'VIEWER',
  STUDENT: 'STUDENT',
  TEACHER: 'TEACHER',
  GUEST: 'GUEST',
  ADMIN: 'ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const SubscriptionStatus = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  CANCELED: 'CANCELED',
  EXPIRED: 'EXPIRED'
} as const

export type SubscriptionStatus = (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus]


export const StreamType = {
  SCHOOL: 'SCHOOL',
  GUEST: 'GUEST'
} as const

export type StreamType = (typeof StreamType)[keyof typeof StreamType]


export const StreamStatus = {
  LIVE: 'LIVE',
  OFFLINE: 'OFFLINE',
  ENDED: 'ENDED'
} as const

export type StreamStatus = (typeof StreamStatus)[keyof typeof StreamStatus]


export const StreamRecordingStatus = {
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED'
} as const

export type StreamRecordingStatus = (typeof StreamRecordingStatus)[keyof typeof StreamRecordingStatus]


export const BundleType = {
  STICKERS: 'STICKERS',
  GIFTS: 'GIFTS'
} as const

export type BundleType = (typeof BundleType)[keyof typeof BundleType]


export const CustomGroupOrderStatus = {
  DRAFT: 'DRAFT',
  CHECKOUT_SENT: 'CHECKOUT_SENT',
  PAID: 'PAID',
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
  CANCELED: 'CANCELED'
} as const

export type CustomGroupOrderStatus = (typeof CustomGroupOrderStatus)[keyof typeof CustomGroupOrderStatus]


export const CustomGroupSeatStatus = {
  AVAILABLE: 'AVAILABLE',
  CLAIMED: 'CLAIMED',
  CANCELED: 'CANCELED'
} as const

export type CustomGroupSeatStatus = (typeof CustomGroupSeatStatus)[keyof typeof CustomGroupSeatStatus]


export const TransactionType = {
  SUBSCRIPTION: 'SUBSCRIPTION',
  SWITCH: 'SWITCH',
  SECOND_SUBSCRIPTION: 'SECOND_SUBSCRIPTION',
  UPGRADE_QNA: 'UPGRADE_QNA',
  STICKER: 'STICKER',
  GIFT: 'GIFT',
  BUNDLE: 'BUNDLE',
  DONATION: 'DONATION',
  INTERNAL_MIRROR: 'INTERNAL_MIRROR'
} as const

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType]


export const Provider = {
  TWOCHECKOUT: 'TWOCHECKOUT'
} as const

export type Provider = (typeof Provider)[keyof typeof Provider]


export const TransactionStatus = {
  PENDING: 'PENDING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED'
} as const

export type TransactionStatus = (typeof TransactionStatus)[keyof typeof TransactionStatus]


export const LikeTargetType = {
  PROFILE: 'PROFILE',
  GRADUATION_WORK: 'GRADUATION_WORK'
} as const

export type LikeTargetType = (typeof LikeTargetType)[keyof typeof LikeTargetType]


export const AdminTaskType = {
  REPORT: 'REPORT',
  FLAG: 'FLAG',
  SUPPORT: 'SUPPORT'
} as const

export type AdminTaskType = (typeof AdminTaskType)[keyof typeof AdminTaskType]


export const AdminTaskStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED'
} as const

export type AdminTaskStatus = (typeof AdminTaskStatus)[keyof typeof AdminTaskStatus]


export const AccountGrantType = {
  FREE_LESSONS: 'FREE_LESSONS'
} as const

export type AccountGrantType = (typeof AccountGrantType)[keyof typeof AccountGrantType]
