
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Graduation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Graduation
 * 
 */
export type GraduationModel = runtime.Types.Result.DefaultSelection<Prisma.$GraduationPayload>

export type AggregateGraduation = {
  _count: GraduationCountAggregateOutputType | null
  _min: GraduationMinAggregateOutputType | null
  _max: GraduationMaxAggregateOutputType | null
}

export type GraduationMinAggregateOutputType = {
  id: string | null
  subscriptionId: string | null
  monthKey: string | null
  eighthUploadId: string | null
  approvedBool: boolean | null
  decidedByTeacherId: string | null
  decidedAt: Date | null
  createdAt: Date | null
}

export type GraduationMaxAggregateOutputType = {
  id: string | null
  subscriptionId: string | null
  monthKey: string | null
  eighthUploadId: string | null
  approvedBool: boolean | null
  decidedByTeacherId: string | null
  decidedAt: Date | null
  createdAt: Date | null
}

export type GraduationCountAggregateOutputType = {
  id: number
  subscriptionId: number
  monthKey: number
  eighthUploadId: number
  approvedBool: number
  decidedByTeacherId: number
  decidedAt: number
  createdAt: number
  _all: number
}


export type GraduationMinAggregateInputType = {
  id?: true
  subscriptionId?: true
  monthKey?: true
  eighthUploadId?: true
  approvedBool?: true
  decidedByTeacherId?: true
  decidedAt?: true
  createdAt?: true
}

export type GraduationMaxAggregateInputType = {
  id?: true
  subscriptionId?: true
  monthKey?: true
  eighthUploadId?: true
  approvedBool?: true
  decidedByTeacherId?: true
  decidedAt?: true
  createdAt?: true
}

export type GraduationCountAggregateInputType = {
  id?: true
  subscriptionId?: true
  monthKey?: true
  eighthUploadId?: true
  approvedBool?: true
  decidedByTeacherId?: true
  decidedAt?: true
  createdAt?: true
  _all?: true
}

export type GraduationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Graduation to aggregate.
   */
  where?: Prisma.GraduationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Graduations to fetch.
   */
  orderBy?: Prisma.GraduationOrderByWithRelationInput | Prisma.GraduationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GraduationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Graduations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Graduations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Graduations
  **/
  _count?: true | GraduationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GraduationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GraduationMaxAggregateInputType
}

export type GetGraduationAggregateType<T extends GraduationAggregateArgs> = {
      [P in keyof T & keyof AggregateGraduation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGraduation[P]>
    : Prisma.GetScalarType<T[P], AggregateGraduation[P]>
}




export type GraduationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GraduationWhereInput
  orderBy?: Prisma.GraduationOrderByWithAggregationInput | Prisma.GraduationOrderByWithAggregationInput[]
  by: Prisma.GraduationScalarFieldEnum[] | Prisma.GraduationScalarFieldEnum
  having?: Prisma.GraduationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GraduationCountAggregateInputType | true
  _min?: GraduationMinAggregateInputType
  _max?: GraduationMaxAggregateInputType
}

export type GraduationGroupByOutputType = {
  id: string
  subscriptionId: string
  monthKey: string
  eighthUploadId: string | null
  approvedBool: boolean | null
  decidedByTeacherId: string | null
  decidedAt: Date | null
  createdAt: Date
  _count: GraduationCountAggregateOutputType | null
  _min: GraduationMinAggregateOutputType | null
  _max: GraduationMaxAggregateOutputType | null
}

type GetGraduationGroupByPayload<T extends GraduationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GraduationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GraduationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GraduationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GraduationGroupByOutputType[P]>
      }
    >
  >



export type GraduationWhereInput = {
  AND?: Prisma.GraduationWhereInput | Prisma.GraduationWhereInput[]
  OR?: Prisma.GraduationWhereInput[]
  NOT?: Prisma.GraduationWhereInput | Prisma.GraduationWhereInput[]
  id?: Prisma.StringFilter<"Graduation"> | string
  subscriptionId?: Prisma.StringFilter<"Graduation"> | string
  monthKey?: Prisma.StringFilter<"Graduation"> | string
  eighthUploadId?: Prisma.StringNullableFilter<"Graduation"> | string | null
  approvedBool?: Prisma.BoolNullableFilter<"Graduation"> | boolean | null
  decidedByTeacherId?: Prisma.StringNullableFilter<"Graduation"> | string | null
  decidedAt?: Prisma.DateTimeNullableFilter<"Graduation"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Graduation"> | Date | string
  subscription?: Prisma.XOR<Prisma.SubscriptionScalarRelationFilter, Prisma.SubscriptionWhereInput>
  eighthUpload?: Prisma.XOR<Prisma.UploadNullableScalarRelationFilter, Prisma.UploadWhereInput> | null
  decidedByTeacher?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type GraduationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  monthKey?: Prisma.SortOrder
  eighthUploadId?: Prisma.SortOrderInput | Prisma.SortOrder
  approvedBool?: Prisma.SortOrderInput | Prisma.SortOrder
  decidedByTeacherId?: Prisma.SortOrderInput | Prisma.SortOrder
  decidedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  subscription?: Prisma.SubscriptionOrderByWithRelationInput
  eighthUpload?: Prisma.UploadOrderByWithRelationInput
  decidedByTeacher?: Prisma.UserOrderByWithRelationInput
}

export type GraduationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  subscriptionId_monthKey?: Prisma.GraduationSubscriptionIdMonthKeyCompoundUniqueInput
  AND?: Prisma.GraduationWhereInput | Prisma.GraduationWhereInput[]
  OR?: Prisma.GraduationWhereInput[]
  NOT?: Prisma.GraduationWhereInput | Prisma.GraduationWhereInput[]
  subscriptionId?: Prisma.StringFilter<"Graduation"> | string
  monthKey?: Prisma.StringFilter<"Graduation"> | string
  eighthUploadId?: Prisma.StringNullableFilter<"Graduation"> | string | null
  approvedBool?: Prisma.BoolNullableFilter<"Graduation"> | boolean | null
  decidedByTeacherId?: Prisma.StringNullableFilter<"Graduation"> | string | null
  decidedAt?: Prisma.DateTimeNullableFilter<"Graduation"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Graduation"> | Date | string
  subscription?: Prisma.XOR<Prisma.SubscriptionScalarRelationFilter, Prisma.SubscriptionWhereInput>
  eighthUpload?: Prisma.XOR<Prisma.UploadNullableScalarRelationFilter, Prisma.UploadWhereInput> | null
  decidedByTeacher?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "subscriptionId_monthKey">

export type GraduationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  monthKey?: Prisma.SortOrder
  eighthUploadId?: Prisma.SortOrderInput | Prisma.SortOrder
  approvedBool?: Prisma.SortOrderInput | Prisma.SortOrder
  decidedByTeacherId?: Prisma.SortOrderInput | Prisma.SortOrder
  decidedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.GraduationCountOrderByAggregateInput
  _max?: Prisma.GraduationMaxOrderByAggregateInput
  _min?: Prisma.GraduationMinOrderByAggregateInput
}

export type GraduationScalarWhereWithAggregatesInput = {
  AND?: Prisma.GraduationScalarWhereWithAggregatesInput | Prisma.GraduationScalarWhereWithAggregatesInput[]
  OR?: Prisma.GraduationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GraduationScalarWhereWithAggregatesInput | Prisma.GraduationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Graduation"> | string
  subscriptionId?: Prisma.StringWithAggregatesFilter<"Graduation"> | string
  monthKey?: Prisma.StringWithAggregatesFilter<"Graduation"> | string
  eighthUploadId?: Prisma.StringNullableWithAggregatesFilter<"Graduation"> | string | null
  approvedBool?: Prisma.BoolNullableWithAggregatesFilter<"Graduation"> | boolean | null
  decidedByTeacherId?: Prisma.StringNullableWithAggregatesFilter<"Graduation"> | string | null
  decidedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Graduation"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Graduation"> | Date | string
}

export type GraduationCreateInput = {
  id?: string
  monthKey: string
  approvedBool?: boolean | null
  decidedAt?: Date | string | null
  createdAt?: Date | string
  subscription: Prisma.SubscriptionCreateNestedOneWithoutGraduationsInput
  eighthUpload?: Prisma.UploadCreateNestedOneWithoutEighthGraduationsInput
  decidedByTeacher?: Prisma.UserCreateNestedOneWithoutGraduationDecisionsInput
}

export type GraduationUncheckedCreateInput = {
  id?: string
  subscriptionId: string
  monthKey: string
  eighthUploadId?: string | null
  approvedBool?: boolean | null
  decidedByTeacherId?: string | null
  decidedAt?: Date | string | null
  createdAt?: Date | string
}

export type GraduationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscription?: Prisma.SubscriptionUpdateOneRequiredWithoutGraduationsNestedInput
  eighthUpload?: Prisma.UploadUpdateOneWithoutEighthGraduationsNestedInput
  decidedByTeacher?: Prisma.UserUpdateOneWithoutGraduationDecisionsNestedInput
}

export type GraduationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  eighthUploadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedByTeacherId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GraduationCreateManyInput = {
  id?: string
  subscriptionId: string
  monthKey: string
  eighthUploadId?: string | null
  approvedBool?: boolean | null
  decidedByTeacherId?: string | null
  decidedAt?: Date | string | null
  createdAt?: Date | string
}

export type GraduationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GraduationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  eighthUploadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedByTeacherId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GraduationListRelationFilter = {
  every?: Prisma.GraduationWhereInput
  some?: Prisma.GraduationWhereInput
  none?: Prisma.GraduationWhereInput
}

export type GraduationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GraduationSubscriptionIdMonthKeyCompoundUniqueInput = {
  subscriptionId: string
  monthKey: string
}

export type GraduationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  monthKey?: Prisma.SortOrder
  eighthUploadId?: Prisma.SortOrder
  approvedBool?: Prisma.SortOrder
  decidedByTeacherId?: Prisma.SortOrder
  decidedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GraduationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  monthKey?: Prisma.SortOrder
  eighthUploadId?: Prisma.SortOrder
  approvedBool?: Prisma.SortOrder
  decidedByTeacherId?: Prisma.SortOrder
  decidedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GraduationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  monthKey?: Prisma.SortOrder
  eighthUploadId?: Prisma.SortOrder
  approvedBool?: Prisma.SortOrder
  decidedByTeacherId?: Prisma.SortOrder
  decidedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GraduationCreateNestedManyWithoutDecidedByTeacherInput = {
  create?: Prisma.XOR<Prisma.GraduationCreateWithoutDecidedByTeacherInput, Prisma.GraduationUncheckedCreateWithoutDecidedByTeacherInput> | Prisma.GraduationCreateWithoutDecidedByTeacherInput[] | Prisma.GraduationUncheckedCreateWithoutDecidedByTeacherInput[]
  connectOrCreate?: Prisma.GraduationCreateOrConnectWithoutDecidedByTeacherInput | Prisma.GraduationCreateOrConnectWithoutDecidedByTeacherInput[]
  createMany?: Prisma.GraduationCreateManyDecidedByTeacherInputEnvelope
  connect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
}

export type GraduationUncheckedCreateNestedManyWithoutDecidedByTeacherInput = {
  create?: Prisma.XOR<Prisma.GraduationCreateWithoutDecidedByTeacherInput, Prisma.GraduationUncheckedCreateWithoutDecidedByTeacherInput> | Prisma.GraduationCreateWithoutDecidedByTeacherInput[] | Prisma.GraduationUncheckedCreateWithoutDecidedByTeacherInput[]
  connectOrCreate?: Prisma.GraduationCreateOrConnectWithoutDecidedByTeacherInput | Prisma.GraduationCreateOrConnectWithoutDecidedByTeacherInput[]
  createMany?: Prisma.GraduationCreateManyDecidedByTeacherInputEnvelope
  connect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
}

export type GraduationUpdateManyWithoutDecidedByTeacherNestedInput = {
  create?: Prisma.XOR<Prisma.GraduationCreateWithoutDecidedByTeacherInput, Prisma.GraduationUncheckedCreateWithoutDecidedByTeacherInput> | Prisma.GraduationCreateWithoutDecidedByTeacherInput[] | Prisma.GraduationUncheckedCreateWithoutDecidedByTeacherInput[]
  connectOrCreate?: Prisma.GraduationCreateOrConnectWithoutDecidedByTeacherInput | Prisma.GraduationCreateOrConnectWithoutDecidedByTeacherInput[]
  upsert?: Prisma.GraduationUpsertWithWhereUniqueWithoutDecidedByTeacherInput | Prisma.GraduationUpsertWithWhereUniqueWithoutDecidedByTeacherInput[]
  createMany?: Prisma.GraduationCreateManyDecidedByTeacherInputEnvelope
  set?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  disconnect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  delete?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  connect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  update?: Prisma.GraduationUpdateWithWhereUniqueWithoutDecidedByTeacherInput | Prisma.GraduationUpdateWithWhereUniqueWithoutDecidedByTeacherInput[]
  updateMany?: Prisma.GraduationUpdateManyWithWhereWithoutDecidedByTeacherInput | Prisma.GraduationUpdateManyWithWhereWithoutDecidedByTeacherInput[]
  deleteMany?: Prisma.GraduationScalarWhereInput | Prisma.GraduationScalarWhereInput[]
}

export type GraduationUncheckedUpdateManyWithoutDecidedByTeacherNestedInput = {
  create?: Prisma.XOR<Prisma.GraduationCreateWithoutDecidedByTeacherInput, Prisma.GraduationUncheckedCreateWithoutDecidedByTeacherInput> | Prisma.GraduationCreateWithoutDecidedByTeacherInput[] | Prisma.GraduationUncheckedCreateWithoutDecidedByTeacherInput[]
  connectOrCreate?: Prisma.GraduationCreateOrConnectWithoutDecidedByTeacherInput | Prisma.GraduationCreateOrConnectWithoutDecidedByTeacherInput[]
  upsert?: Prisma.GraduationUpsertWithWhereUniqueWithoutDecidedByTeacherInput | Prisma.GraduationUpsertWithWhereUniqueWithoutDecidedByTeacherInput[]
  createMany?: Prisma.GraduationCreateManyDecidedByTeacherInputEnvelope
  set?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  disconnect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  delete?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  connect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  update?: Prisma.GraduationUpdateWithWhereUniqueWithoutDecidedByTeacherInput | Prisma.GraduationUpdateWithWhereUniqueWithoutDecidedByTeacherInput[]
  updateMany?: Prisma.GraduationUpdateManyWithWhereWithoutDecidedByTeacherInput | Prisma.GraduationUpdateManyWithWhereWithoutDecidedByTeacherInput[]
  deleteMany?: Prisma.GraduationScalarWhereInput | Prisma.GraduationScalarWhereInput[]
}

export type GraduationCreateNestedManyWithoutSubscriptionInput = {
  create?: Prisma.XOR<Prisma.GraduationCreateWithoutSubscriptionInput, Prisma.GraduationUncheckedCreateWithoutSubscriptionInput> | Prisma.GraduationCreateWithoutSubscriptionInput[] | Prisma.GraduationUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.GraduationCreateOrConnectWithoutSubscriptionInput | Prisma.GraduationCreateOrConnectWithoutSubscriptionInput[]
  createMany?: Prisma.GraduationCreateManySubscriptionInputEnvelope
  connect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
}

export type GraduationUncheckedCreateNestedManyWithoutSubscriptionInput = {
  create?: Prisma.XOR<Prisma.GraduationCreateWithoutSubscriptionInput, Prisma.GraduationUncheckedCreateWithoutSubscriptionInput> | Prisma.GraduationCreateWithoutSubscriptionInput[] | Prisma.GraduationUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.GraduationCreateOrConnectWithoutSubscriptionInput | Prisma.GraduationCreateOrConnectWithoutSubscriptionInput[]
  createMany?: Prisma.GraduationCreateManySubscriptionInputEnvelope
  connect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
}

export type GraduationUpdateManyWithoutSubscriptionNestedInput = {
  create?: Prisma.XOR<Prisma.GraduationCreateWithoutSubscriptionInput, Prisma.GraduationUncheckedCreateWithoutSubscriptionInput> | Prisma.GraduationCreateWithoutSubscriptionInput[] | Prisma.GraduationUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.GraduationCreateOrConnectWithoutSubscriptionInput | Prisma.GraduationCreateOrConnectWithoutSubscriptionInput[]
  upsert?: Prisma.GraduationUpsertWithWhereUniqueWithoutSubscriptionInput | Prisma.GraduationUpsertWithWhereUniqueWithoutSubscriptionInput[]
  createMany?: Prisma.GraduationCreateManySubscriptionInputEnvelope
  set?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  disconnect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  delete?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  connect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  update?: Prisma.GraduationUpdateWithWhereUniqueWithoutSubscriptionInput | Prisma.GraduationUpdateWithWhereUniqueWithoutSubscriptionInput[]
  updateMany?: Prisma.GraduationUpdateManyWithWhereWithoutSubscriptionInput | Prisma.GraduationUpdateManyWithWhereWithoutSubscriptionInput[]
  deleteMany?: Prisma.GraduationScalarWhereInput | Prisma.GraduationScalarWhereInput[]
}

export type GraduationUncheckedUpdateManyWithoutSubscriptionNestedInput = {
  create?: Prisma.XOR<Prisma.GraduationCreateWithoutSubscriptionInput, Prisma.GraduationUncheckedCreateWithoutSubscriptionInput> | Prisma.GraduationCreateWithoutSubscriptionInput[] | Prisma.GraduationUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.GraduationCreateOrConnectWithoutSubscriptionInput | Prisma.GraduationCreateOrConnectWithoutSubscriptionInput[]
  upsert?: Prisma.GraduationUpsertWithWhereUniqueWithoutSubscriptionInput | Prisma.GraduationUpsertWithWhereUniqueWithoutSubscriptionInput[]
  createMany?: Prisma.GraduationCreateManySubscriptionInputEnvelope
  set?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  disconnect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  delete?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  connect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  update?: Prisma.GraduationUpdateWithWhereUniqueWithoutSubscriptionInput | Prisma.GraduationUpdateWithWhereUniqueWithoutSubscriptionInput[]
  updateMany?: Prisma.GraduationUpdateManyWithWhereWithoutSubscriptionInput | Prisma.GraduationUpdateManyWithWhereWithoutSubscriptionInput[]
  deleteMany?: Prisma.GraduationScalarWhereInput | Prisma.GraduationScalarWhereInput[]
}

export type GraduationCreateNestedManyWithoutEighthUploadInput = {
  create?: Prisma.XOR<Prisma.GraduationCreateWithoutEighthUploadInput, Prisma.GraduationUncheckedCreateWithoutEighthUploadInput> | Prisma.GraduationCreateWithoutEighthUploadInput[] | Prisma.GraduationUncheckedCreateWithoutEighthUploadInput[]
  connectOrCreate?: Prisma.GraduationCreateOrConnectWithoutEighthUploadInput | Prisma.GraduationCreateOrConnectWithoutEighthUploadInput[]
  createMany?: Prisma.GraduationCreateManyEighthUploadInputEnvelope
  connect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
}

export type GraduationUncheckedCreateNestedManyWithoutEighthUploadInput = {
  create?: Prisma.XOR<Prisma.GraduationCreateWithoutEighthUploadInput, Prisma.GraduationUncheckedCreateWithoutEighthUploadInput> | Prisma.GraduationCreateWithoutEighthUploadInput[] | Prisma.GraduationUncheckedCreateWithoutEighthUploadInput[]
  connectOrCreate?: Prisma.GraduationCreateOrConnectWithoutEighthUploadInput | Prisma.GraduationCreateOrConnectWithoutEighthUploadInput[]
  createMany?: Prisma.GraduationCreateManyEighthUploadInputEnvelope
  connect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
}

export type GraduationUpdateManyWithoutEighthUploadNestedInput = {
  create?: Prisma.XOR<Prisma.GraduationCreateWithoutEighthUploadInput, Prisma.GraduationUncheckedCreateWithoutEighthUploadInput> | Prisma.GraduationCreateWithoutEighthUploadInput[] | Prisma.GraduationUncheckedCreateWithoutEighthUploadInput[]
  connectOrCreate?: Prisma.GraduationCreateOrConnectWithoutEighthUploadInput | Prisma.GraduationCreateOrConnectWithoutEighthUploadInput[]
  upsert?: Prisma.GraduationUpsertWithWhereUniqueWithoutEighthUploadInput | Prisma.GraduationUpsertWithWhereUniqueWithoutEighthUploadInput[]
  createMany?: Prisma.GraduationCreateManyEighthUploadInputEnvelope
  set?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  disconnect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  delete?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  connect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  update?: Prisma.GraduationUpdateWithWhereUniqueWithoutEighthUploadInput | Prisma.GraduationUpdateWithWhereUniqueWithoutEighthUploadInput[]
  updateMany?: Prisma.GraduationUpdateManyWithWhereWithoutEighthUploadInput | Prisma.GraduationUpdateManyWithWhereWithoutEighthUploadInput[]
  deleteMany?: Prisma.GraduationScalarWhereInput | Prisma.GraduationScalarWhereInput[]
}

export type GraduationUncheckedUpdateManyWithoutEighthUploadNestedInput = {
  create?: Prisma.XOR<Prisma.GraduationCreateWithoutEighthUploadInput, Prisma.GraduationUncheckedCreateWithoutEighthUploadInput> | Prisma.GraduationCreateWithoutEighthUploadInput[] | Prisma.GraduationUncheckedCreateWithoutEighthUploadInput[]
  connectOrCreate?: Prisma.GraduationCreateOrConnectWithoutEighthUploadInput | Prisma.GraduationCreateOrConnectWithoutEighthUploadInput[]
  upsert?: Prisma.GraduationUpsertWithWhereUniqueWithoutEighthUploadInput | Prisma.GraduationUpsertWithWhereUniqueWithoutEighthUploadInput[]
  createMany?: Prisma.GraduationCreateManyEighthUploadInputEnvelope
  set?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  disconnect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  delete?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  connect?: Prisma.GraduationWhereUniqueInput | Prisma.GraduationWhereUniqueInput[]
  update?: Prisma.GraduationUpdateWithWhereUniqueWithoutEighthUploadInput | Prisma.GraduationUpdateWithWhereUniqueWithoutEighthUploadInput[]
  updateMany?: Prisma.GraduationUpdateManyWithWhereWithoutEighthUploadInput | Prisma.GraduationUpdateManyWithWhereWithoutEighthUploadInput[]
  deleteMany?: Prisma.GraduationScalarWhereInput | Prisma.GraduationScalarWhereInput[]
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type GraduationCreateWithoutDecidedByTeacherInput = {
  id?: string
  monthKey: string
  approvedBool?: boolean | null
  decidedAt?: Date | string | null
  createdAt?: Date | string
  subscription: Prisma.SubscriptionCreateNestedOneWithoutGraduationsInput
  eighthUpload?: Prisma.UploadCreateNestedOneWithoutEighthGraduationsInput
}

export type GraduationUncheckedCreateWithoutDecidedByTeacherInput = {
  id?: string
  subscriptionId: string
  monthKey: string
  eighthUploadId?: string | null
  approvedBool?: boolean | null
  decidedAt?: Date | string | null
  createdAt?: Date | string
}

export type GraduationCreateOrConnectWithoutDecidedByTeacherInput = {
  where: Prisma.GraduationWhereUniqueInput
  create: Prisma.XOR<Prisma.GraduationCreateWithoutDecidedByTeacherInput, Prisma.GraduationUncheckedCreateWithoutDecidedByTeacherInput>
}

export type GraduationCreateManyDecidedByTeacherInputEnvelope = {
  data: Prisma.GraduationCreateManyDecidedByTeacherInput | Prisma.GraduationCreateManyDecidedByTeacherInput[]
  skipDuplicates?: boolean
}

export type GraduationUpsertWithWhereUniqueWithoutDecidedByTeacherInput = {
  where: Prisma.GraduationWhereUniqueInput
  update: Prisma.XOR<Prisma.GraduationUpdateWithoutDecidedByTeacherInput, Prisma.GraduationUncheckedUpdateWithoutDecidedByTeacherInput>
  create: Prisma.XOR<Prisma.GraduationCreateWithoutDecidedByTeacherInput, Prisma.GraduationUncheckedCreateWithoutDecidedByTeacherInput>
}

export type GraduationUpdateWithWhereUniqueWithoutDecidedByTeacherInput = {
  where: Prisma.GraduationWhereUniqueInput
  data: Prisma.XOR<Prisma.GraduationUpdateWithoutDecidedByTeacherInput, Prisma.GraduationUncheckedUpdateWithoutDecidedByTeacherInput>
}

export type GraduationUpdateManyWithWhereWithoutDecidedByTeacherInput = {
  where: Prisma.GraduationScalarWhereInput
  data: Prisma.XOR<Prisma.GraduationUpdateManyMutationInput, Prisma.GraduationUncheckedUpdateManyWithoutDecidedByTeacherInput>
}

export type GraduationScalarWhereInput = {
  AND?: Prisma.GraduationScalarWhereInput | Prisma.GraduationScalarWhereInput[]
  OR?: Prisma.GraduationScalarWhereInput[]
  NOT?: Prisma.GraduationScalarWhereInput | Prisma.GraduationScalarWhereInput[]
  id?: Prisma.StringFilter<"Graduation"> | string
  subscriptionId?: Prisma.StringFilter<"Graduation"> | string
  monthKey?: Prisma.StringFilter<"Graduation"> | string
  eighthUploadId?: Prisma.StringNullableFilter<"Graduation"> | string | null
  approvedBool?: Prisma.BoolNullableFilter<"Graduation"> | boolean | null
  decidedByTeacherId?: Prisma.StringNullableFilter<"Graduation"> | string | null
  decidedAt?: Prisma.DateTimeNullableFilter<"Graduation"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Graduation"> | Date | string
}

export type GraduationCreateWithoutSubscriptionInput = {
  id?: string
  monthKey: string
  approvedBool?: boolean | null
  decidedAt?: Date | string | null
  createdAt?: Date | string
  eighthUpload?: Prisma.UploadCreateNestedOneWithoutEighthGraduationsInput
  decidedByTeacher?: Prisma.UserCreateNestedOneWithoutGraduationDecisionsInput
}

export type GraduationUncheckedCreateWithoutSubscriptionInput = {
  id?: string
  monthKey: string
  eighthUploadId?: string | null
  approvedBool?: boolean | null
  decidedByTeacherId?: string | null
  decidedAt?: Date | string | null
  createdAt?: Date | string
}

export type GraduationCreateOrConnectWithoutSubscriptionInput = {
  where: Prisma.GraduationWhereUniqueInput
  create: Prisma.XOR<Prisma.GraduationCreateWithoutSubscriptionInput, Prisma.GraduationUncheckedCreateWithoutSubscriptionInput>
}

export type GraduationCreateManySubscriptionInputEnvelope = {
  data: Prisma.GraduationCreateManySubscriptionInput | Prisma.GraduationCreateManySubscriptionInput[]
  skipDuplicates?: boolean
}

export type GraduationUpsertWithWhereUniqueWithoutSubscriptionInput = {
  where: Prisma.GraduationWhereUniqueInput
  update: Prisma.XOR<Prisma.GraduationUpdateWithoutSubscriptionInput, Prisma.GraduationUncheckedUpdateWithoutSubscriptionInput>
  create: Prisma.XOR<Prisma.GraduationCreateWithoutSubscriptionInput, Prisma.GraduationUncheckedCreateWithoutSubscriptionInput>
}

export type GraduationUpdateWithWhereUniqueWithoutSubscriptionInput = {
  where: Prisma.GraduationWhereUniqueInput
  data: Prisma.XOR<Prisma.GraduationUpdateWithoutSubscriptionInput, Prisma.GraduationUncheckedUpdateWithoutSubscriptionInput>
}

export type GraduationUpdateManyWithWhereWithoutSubscriptionInput = {
  where: Prisma.GraduationScalarWhereInput
  data: Prisma.XOR<Prisma.GraduationUpdateManyMutationInput, Prisma.GraduationUncheckedUpdateManyWithoutSubscriptionInput>
}

export type GraduationCreateWithoutEighthUploadInput = {
  id?: string
  monthKey: string
  approvedBool?: boolean | null
  decidedAt?: Date | string | null
  createdAt?: Date | string
  subscription: Prisma.SubscriptionCreateNestedOneWithoutGraduationsInput
  decidedByTeacher?: Prisma.UserCreateNestedOneWithoutGraduationDecisionsInput
}

export type GraduationUncheckedCreateWithoutEighthUploadInput = {
  id?: string
  subscriptionId: string
  monthKey: string
  approvedBool?: boolean | null
  decidedByTeacherId?: string | null
  decidedAt?: Date | string | null
  createdAt?: Date | string
}

export type GraduationCreateOrConnectWithoutEighthUploadInput = {
  where: Prisma.GraduationWhereUniqueInput
  create: Prisma.XOR<Prisma.GraduationCreateWithoutEighthUploadInput, Prisma.GraduationUncheckedCreateWithoutEighthUploadInput>
}

export type GraduationCreateManyEighthUploadInputEnvelope = {
  data: Prisma.GraduationCreateManyEighthUploadInput | Prisma.GraduationCreateManyEighthUploadInput[]
  skipDuplicates?: boolean
}

export type GraduationUpsertWithWhereUniqueWithoutEighthUploadInput = {
  where: Prisma.GraduationWhereUniqueInput
  update: Prisma.XOR<Prisma.GraduationUpdateWithoutEighthUploadInput, Prisma.GraduationUncheckedUpdateWithoutEighthUploadInput>
  create: Prisma.XOR<Prisma.GraduationCreateWithoutEighthUploadInput, Prisma.GraduationUncheckedCreateWithoutEighthUploadInput>
}

export type GraduationUpdateWithWhereUniqueWithoutEighthUploadInput = {
  where: Prisma.GraduationWhereUniqueInput
  data: Prisma.XOR<Prisma.GraduationUpdateWithoutEighthUploadInput, Prisma.GraduationUncheckedUpdateWithoutEighthUploadInput>
}

export type GraduationUpdateManyWithWhereWithoutEighthUploadInput = {
  where: Prisma.GraduationScalarWhereInput
  data: Prisma.XOR<Prisma.GraduationUpdateManyMutationInput, Prisma.GraduationUncheckedUpdateManyWithoutEighthUploadInput>
}

export type GraduationCreateManyDecidedByTeacherInput = {
  id?: string
  subscriptionId: string
  monthKey: string
  eighthUploadId?: string | null
  approvedBool?: boolean | null
  decidedAt?: Date | string | null
  createdAt?: Date | string
}

export type GraduationUpdateWithoutDecidedByTeacherInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscription?: Prisma.SubscriptionUpdateOneRequiredWithoutGraduationsNestedInput
  eighthUpload?: Prisma.UploadUpdateOneWithoutEighthGraduationsNestedInput
}

export type GraduationUncheckedUpdateWithoutDecidedByTeacherInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  eighthUploadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GraduationUncheckedUpdateManyWithoutDecidedByTeacherInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  eighthUploadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GraduationCreateManySubscriptionInput = {
  id?: string
  monthKey: string
  eighthUploadId?: string | null
  approvedBool?: boolean | null
  decidedByTeacherId?: string | null
  decidedAt?: Date | string | null
  createdAt?: Date | string
}

export type GraduationUpdateWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eighthUpload?: Prisma.UploadUpdateOneWithoutEighthGraduationsNestedInput
  decidedByTeacher?: Prisma.UserUpdateOneWithoutGraduationDecisionsNestedInput
}

export type GraduationUncheckedUpdateWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  eighthUploadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedByTeacherId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GraduationUncheckedUpdateManyWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  eighthUploadId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedByTeacherId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GraduationCreateManyEighthUploadInput = {
  id?: string
  subscriptionId: string
  monthKey: string
  approvedBool?: boolean | null
  decidedByTeacherId?: string | null
  decidedAt?: Date | string | null
  createdAt?: Date | string
}

export type GraduationUpdateWithoutEighthUploadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscription?: Prisma.SubscriptionUpdateOneRequiredWithoutGraduationsNestedInput
  decidedByTeacher?: Prisma.UserUpdateOneWithoutGraduationDecisionsNestedInput
}

export type GraduationUncheckedUpdateWithoutEighthUploadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedByTeacherId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GraduationUncheckedUpdateManyWithoutEighthUploadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  monthKey?: Prisma.StringFieldUpdateOperationsInput | string
  approvedBool?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  decidedByTeacherId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  decidedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type GraduationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  subscriptionId?: boolean
  monthKey?: boolean
  eighthUploadId?: boolean
  approvedBool?: boolean
  decidedByTeacherId?: boolean
  decidedAt?: boolean
  createdAt?: boolean
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  eighthUpload?: boolean | Prisma.Graduation$eighthUploadArgs<ExtArgs>
  decidedByTeacher?: boolean | Prisma.Graduation$decidedByTeacherArgs<ExtArgs>
}, ExtArgs["result"]["graduation"]>

export type GraduationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  subscriptionId?: boolean
  monthKey?: boolean
  eighthUploadId?: boolean
  approvedBool?: boolean
  decidedByTeacherId?: boolean
  decidedAt?: boolean
  createdAt?: boolean
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  eighthUpload?: boolean | Prisma.Graduation$eighthUploadArgs<ExtArgs>
  decidedByTeacher?: boolean | Prisma.Graduation$decidedByTeacherArgs<ExtArgs>
}, ExtArgs["result"]["graduation"]>

export type GraduationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  subscriptionId?: boolean
  monthKey?: boolean
  eighthUploadId?: boolean
  approvedBool?: boolean
  decidedByTeacherId?: boolean
  decidedAt?: boolean
  createdAt?: boolean
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  eighthUpload?: boolean | Prisma.Graduation$eighthUploadArgs<ExtArgs>
  decidedByTeacher?: boolean | Prisma.Graduation$decidedByTeacherArgs<ExtArgs>
}, ExtArgs["result"]["graduation"]>

export type GraduationSelectScalar = {
  id?: boolean
  subscriptionId?: boolean
  monthKey?: boolean
  eighthUploadId?: boolean
  approvedBool?: boolean
  decidedByTeacherId?: boolean
  decidedAt?: boolean
  createdAt?: boolean
}

export type GraduationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "subscriptionId" | "monthKey" | "eighthUploadId" | "approvedBool" | "decidedByTeacherId" | "decidedAt" | "createdAt", ExtArgs["result"]["graduation"]>
export type GraduationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  eighthUpload?: boolean | Prisma.Graduation$eighthUploadArgs<ExtArgs>
  decidedByTeacher?: boolean | Prisma.Graduation$decidedByTeacherArgs<ExtArgs>
}
export type GraduationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  eighthUpload?: boolean | Prisma.Graduation$eighthUploadArgs<ExtArgs>
  decidedByTeacher?: boolean | Prisma.Graduation$decidedByTeacherArgs<ExtArgs>
}
export type GraduationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  eighthUpload?: boolean | Prisma.Graduation$eighthUploadArgs<ExtArgs>
  decidedByTeacher?: boolean | Prisma.Graduation$decidedByTeacherArgs<ExtArgs>
}

export type $GraduationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Graduation"
  objects: {
    subscription: Prisma.$SubscriptionPayload<ExtArgs>
    eighthUpload: Prisma.$UploadPayload<ExtArgs> | null
    decidedByTeacher: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    subscriptionId: string
    monthKey: string
    eighthUploadId: string | null
    approvedBool: boolean | null
    decidedByTeacherId: string | null
    decidedAt: Date | null
    createdAt: Date
  }, ExtArgs["result"]["graduation"]>
  composites: {}
}

export type GraduationGetPayload<S extends boolean | null | undefined | GraduationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GraduationPayload, S>

export type GraduationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GraduationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GraduationCountAggregateInputType | true
  }

export interface GraduationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Graduation'], meta: { name: 'Graduation' } }
  /**
   * Find zero or one Graduation that matches the filter.
   * @param {GraduationFindUniqueArgs} args - Arguments to find a Graduation
   * @example
   * // Get one Graduation
   * const graduation = await prisma.graduation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GraduationFindUniqueArgs>(args: Prisma.SelectSubset<T, GraduationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GraduationClient<runtime.Types.Result.GetResult<Prisma.$GraduationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Graduation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GraduationFindUniqueOrThrowArgs} args - Arguments to find a Graduation
   * @example
   * // Get one Graduation
   * const graduation = await prisma.graduation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GraduationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GraduationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GraduationClient<runtime.Types.Result.GetResult<Prisma.$GraduationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Graduation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GraduationFindFirstArgs} args - Arguments to find a Graduation
   * @example
   * // Get one Graduation
   * const graduation = await prisma.graduation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GraduationFindFirstArgs>(args?: Prisma.SelectSubset<T, GraduationFindFirstArgs<ExtArgs>>): Prisma.Prisma__GraduationClient<runtime.Types.Result.GetResult<Prisma.$GraduationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Graduation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GraduationFindFirstOrThrowArgs} args - Arguments to find a Graduation
   * @example
   * // Get one Graduation
   * const graduation = await prisma.graduation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GraduationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GraduationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GraduationClient<runtime.Types.Result.GetResult<Prisma.$GraduationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Graduations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GraduationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Graduations
   * const graduations = await prisma.graduation.findMany()
   * 
   * // Get first 10 Graduations
   * const graduations = await prisma.graduation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const graduationWithIdOnly = await prisma.graduation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GraduationFindManyArgs>(args?: Prisma.SelectSubset<T, GraduationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GraduationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Graduation.
   * @param {GraduationCreateArgs} args - Arguments to create a Graduation.
   * @example
   * // Create one Graduation
   * const Graduation = await prisma.graduation.create({
   *   data: {
   *     // ... data to create a Graduation
   *   }
   * })
   * 
   */
  create<T extends GraduationCreateArgs>(args: Prisma.SelectSubset<T, GraduationCreateArgs<ExtArgs>>): Prisma.Prisma__GraduationClient<runtime.Types.Result.GetResult<Prisma.$GraduationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Graduations.
   * @param {GraduationCreateManyArgs} args - Arguments to create many Graduations.
   * @example
   * // Create many Graduations
   * const graduation = await prisma.graduation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GraduationCreateManyArgs>(args?: Prisma.SelectSubset<T, GraduationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Graduations and returns the data saved in the database.
   * @param {GraduationCreateManyAndReturnArgs} args - Arguments to create many Graduations.
   * @example
   * // Create many Graduations
   * const graduation = await prisma.graduation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Graduations and only return the `id`
   * const graduationWithIdOnly = await prisma.graduation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GraduationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GraduationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GraduationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Graduation.
   * @param {GraduationDeleteArgs} args - Arguments to delete one Graduation.
   * @example
   * // Delete one Graduation
   * const Graduation = await prisma.graduation.delete({
   *   where: {
   *     // ... filter to delete one Graduation
   *   }
   * })
   * 
   */
  delete<T extends GraduationDeleteArgs>(args: Prisma.SelectSubset<T, GraduationDeleteArgs<ExtArgs>>): Prisma.Prisma__GraduationClient<runtime.Types.Result.GetResult<Prisma.$GraduationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Graduation.
   * @param {GraduationUpdateArgs} args - Arguments to update one Graduation.
   * @example
   * // Update one Graduation
   * const graduation = await prisma.graduation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GraduationUpdateArgs>(args: Prisma.SelectSubset<T, GraduationUpdateArgs<ExtArgs>>): Prisma.Prisma__GraduationClient<runtime.Types.Result.GetResult<Prisma.$GraduationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Graduations.
   * @param {GraduationDeleteManyArgs} args - Arguments to filter Graduations to delete.
   * @example
   * // Delete a few Graduations
   * const { count } = await prisma.graduation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GraduationDeleteManyArgs>(args?: Prisma.SelectSubset<T, GraduationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Graduations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GraduationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Graduations
   * const graduation = await prisma.graduation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GraduationUpdateManyArgs>(args: Prisma.SelectSubset<T, GraduationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Graduations and returns the data updated in the database.
   * @param {GraduationUpdateManyAndReturnArgs} args - Arguments to update many Graduations.
   * @example
   * // Update many Graduations
   * const graduation = await prisma.graduation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Graduations and only return the `id`
   * const graduationWithIdOnly = await prisma.graduation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GraduationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GraduationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GraduationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Graduation.
   * @param {GraduationUpsertArgs} args - Arguments to update or create a Graduation.
   * @example
   * // Update or create a Graduation
   * const graduation = await prisma.graduation.upsert({
   *   create: {
   *     // ... data to create a Graduation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Graduation we want to update
   *   }
   * })
   */
  upsert<T extends GraduationUpsertArgs>(args: Prisma.SelectSubset<T, GraduationUpsertArgs<ExtArgs>>): Prisma.Prisma__GraduationClient<runtime.Types.Result.GetResult<Prisma.$GraduationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Graduations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GraduationCountArgs} args - Arguments to filter Graduations to count.
   * @example
   * // Count the number of Graduations
   * const count = await prisma.graduation.count({
   *   where: {
   *     // ... the filter for the Graduations we want to count
   *   }
   * })
  **/
  count<T extends GraduationCountArgs>(
    args?: Prisma.Subset<T, GraduationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GraduationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Graduation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GraduationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GraduationAggregateArgs>(args: Prisma.Subset<T, GraduationAggregateArgs>): Prisma.PrismaPromise<GetGraduationAggregateType<T>>

  /**
   * Group by Graduation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GraduationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GraduationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GraduationGroupByArgs['orderBy'] }
      : { orderBy?: GraduationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GraduationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGraduationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Graduation model
 */
readonly fields: GraduationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Graduation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GraduationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  subscription<T extends Prisma.SubscriptionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubscriptionDefaultArgs<ExtArgs>>): Prisma.Prisma__SubscriptionClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  eighthUpload<T extends Prisma.Graduation$eighthUploadArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Graduation$eighthUploadArgs<ExtArgs>>): Prisma.Prisma__UploadClient<runtime.Types.Result.GetResult<Prisma.$UploadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  decidedByTeacher<T extends Prisma.Graduation$decidedByTeacherArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Graduation$decidedByTeacherArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Graduation model
 */
export interface GraduationFieldRefs {
  readonly id: Prisma.FieldRef<"Graduation", 'String'>
  readonly subscriptionId: Prisma.FieldRef<"Graduation", 'String'>
  readonly monthKey: Prisma.FieldRef<"Graduation", 'String'>
  readonly eighthUploadId: Prisma.FieldRef<"Graduation", 'String'>
  readonly approvedBool: Prisma.FieldRef<"Graduation", 'Boolean'>
  readonly decidedByTeacherId: Prisma.FieldRef<"Graduation", 'String'>
  readonly decidedAt: Prisma.FieldRef<"Graduation", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Graduation", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Graduation findUnique
 */
export type GraduationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationInclude<ExtArgs> | null
  /**
   * Filter, which Graduation to fetch.
   */
  where: Prisma.GraduationWhereUniqueInput
}

/**
 * Graduation findUniqueOrThrow
 */
export type GraduationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationInclude<ExtArgs> | null
  /**
   * Filter, which Graduation to fetch.
   */
  where: Prisma.GraduationWhereUniqueInput
}

/**
 * Graduation findFirst
 */
export type GraduationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationInclude<ExtArgs> | null
  /**
   * Filter, which Graduation to fetch.
   */
  where?: Prisma.GraduationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Graduations to fetch.
   */
  orderBy?: Prisma.GraduationOrderByWithRelationInput | Prisma.GraduationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Graduations.
   */
  cursor?: Prisma.GraduationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Graduations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Graduations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Graduations.
   */
  distinct?: Prisma.GraduationScalarFieldEnum | Prisma.GraduationScalarFieldEnum[]
}

/**
 * Graduation findFirstOrThrow
 */
export type GraduationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationInclude<ExtArgs> | null
  /**
   * Filter, which Graduation to fetch.
   */
  where?: Prisma.GraduationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Graduations to fetch.
   */
  orderBy?: Prisma.GraduationOrderByWithRelationInput | Prisma.GraduationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Graduations.
   */
  cursor?: Prisma.GraduationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Graduations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Graduations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Graduations.
   */
  distinct?: Prisma.GraduationScalarFieldEnum | Prisma.GraduationScalarFieldEnum[]
}

/**
 * Graduation findMany
 */
export type GraduationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationInclude<ExtArgs> | null
  /**
   * Filter, which Graduations to fetch.
   */
  where?: Prisma.GraduationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Graduations to fetch.
   */
  orderBy?: Prisma.GraduationOrderByWithRelationInput | Prisma.GraduationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Graduations.
   */
  cursor?: Prisma.GraduationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Graduations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Graduations.
   */
  skip?: number
  distinct?: Prisma.GraduationScalarFieldEnum | Prisma.GraduationScalarFieldEnum[]
}

/**
 * Graduation create
 */
export type GraduationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationInclude<ExtArgs> | null
  /**
   * The data needed to create a Graduation.
   */
  data: Prisma.XOR<Prisma.GraduationCreateInput, Prisma.GraduationUncheckedCreateInput>
}

/**
 * Graduation createMany
 */
export type GraduationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Graduations.
   */
  data: Prisma.GraduationCreateManyInput | Prisma.GraduationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Graduation createManyAndReturn
 */
export type GraduationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * The data used to create many Graduations.
   */
  data: Prisma.GraduationCreateManyInput | Prisma.GraduationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Graduation update
 */
export type GraduationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationInclude<ExtArgs> | null
  /**
   * The data needed to update a Graduation.
   */
  data: Prisma.XOR<Prisma.GraduationUpdateInput, Prisma.GraduationUncheckedUpdateInput>
  /**
   * Choose, which Graduation to update.
   */
  where: Prisma.GraduationWhereUniqueInput
}

/**
 * Graduation updateMany
 */
export type GraduationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Graduations.
   */
  data: Prisma.XOR<Prisma.GraduationUpdateManyMutationInput, Prisma.GraduationUncheckedUpdateManyInput>
  /**
   * Filter which Graduations to update
   */
  where?: Prisma.GraduationWhereInput
  /**
   * Limit how many Graduations to update.
   */
  limit?: number
}

/**
 * Graduation updateManyAndReturn
 */
export type GraduationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * The data used to update Graduations.
   */
  data: Prisma.XOR<Prisma.GraduationUpdateManyMutationInput, Prisma.GraduationUncheckedUpdateManyInput>
  /**
   * Filter which Graduations to update
   */
  where?: Prisma.GraduationWhereInput
  /**
   * Limit how many Graduations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Graduation upsert
 */
export type GraduationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationInclude<ExtArgs> | null
  /**
   * The filter to search for the Graduation to update in case it exists.
   */
  where: Prisma.GraduationWhereUniqueInput
  /**
   * In case the Graduation found by the `where` argument doesn't exist, create a new Graduation with this data.
   */
  create: Prisma.XOR<Prisma.GraduationCreateInput, Prisma.GraduationUncheckedCreateInput>
  /**
   * In case the Graduation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GraduationUpdateInput, Prisma.GraduationUncheckedUpdateInput>
}

/**
 * Graduation delete
 */
export type GraduationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationInclude<ExtArgs> | null
  /**
   * Filter which Graduation to delete.
   */
  where: Prisma.GraduationWhereUniqueInput
}

/**
 * Graduation deleteMany
 */
export type GraduationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Graduations to delete
   */
  where?: Prisma.GraduationWhereInput
  /**
   * Limit how many Graduations to delete.
   */
  limit?: number
}

/**
 * Graduation.eighthUpload
 */
export type Graduation$eighthUploadArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadInclude<ExtArgs> | null
  where?: Prisma.UploadWhereInput
}

/**
 * Graduation.decidedByTeacher
 */
export type Graduation$decidedByTeacherArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Graduation without action
 */
export type GraduationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationInclude<ExtArgs> | null
}
