
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PageContentBlock` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PageContentBlock
 * 
 */
export type PageContentBlockModel = runtime.Types.Result.DefaultSelection<Prisma.$PageContentBlockPayload>

export type AggregatePageContentBlock = {
  _count: PageContentBlockCountAggregateOutputType | null
  _avg: PageContentBlockAvgAggregateOutputType | null
  _sum: PageContentBlockSumAggregateOutputType | null
  _min: PageContentBlockMinAggregateOutputType | null
  _max: PageContentBlockMaxAggregateOutputType | null
}

export type PageContentBlockAvgAggregateOutputType = {
  sortOrder: number | null
}

export type PageContentBlockSumAggregateOutputType = {
  sortOrder: number | null
}

export type PageContentBlockMinAggregateOutputType = {
  id: string | null
  pageKey: string | null
  sectionKey: string | null
  title: string | null
  bodyText: string | null
  ctaLabel: string | null
  ctaHref: string | null
  ctaSecondaryLabel: string | null
  ctaSecondaryHref: string | null
  imageUrl: string | null
  sortOrder: number | null
  isPublished: boolean | null
  updatedByAdminId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PageContentBlockMaxAggregateOutputType = {
  id: string | null
  pageKey: string | null
  sectionKey: string | null
  title: string | null
  bodyText: string | null
  ctaLabel: string | null
  ctaHref: string | null
  ctaSecondaryLabel: string | null
  ctaSecondaryHref: string | null
  imageUrl: string | null
  sortOrder: number | null
  isPublished: boolean | null
  updatedByAdminId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PageContentBlockCountAggregateOutputType = {
  id: number
  pageKey: number
  sectionKey: number
  title: number
  bodyText: number
  ctaLabel: number
  ctaHref: number
  ctaSecondaryLabel: number
  ctaSecondaryHref: number
  imageUrl: number
  sortOrder: number
  isPublished: number
  updatedByAdminId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PageContentBlockAvgAggregateInputType = {
  sortOrder?: true
}

export type PageContentBlockSumAggregateInputType = {
  sortOrder?: true
}

export type PageContentBlockMinAggregateInputType = {
  id?: true
  pageKey?: true
  sectionKey?: true
  title?: true
  bodyText?: true
  ctaLabel?: true
  ctaHref?: true
  ctaSecondaryLabel?: true
  ctaSecondaryHref?: true
  imageUrl?: true
  sortOrder?: true
  isPublished?: true
  updatedByAdminId?: true
  createdAt?: true
  updatedAt?: true
}

export type PageContentBlockMaxAggregateInputType = {
  id?: true
  pageKey?: true
  sectionKey?: true
  title?: true
  bodyText?: true
  ctaLabel?: true
  ctaHref?: true
  ctaSecondaryLabel?: true
  ctaSecondaryHref?: true
  imageUrl?: true
  sortOrder?: true
  isPublished?: true
  updatedByAdminId?: true
  createdAt?: true
  updatedAt?: true
}

export type PageContentBlockCountAggregateInputType = {
  id?: true
  pageKey?: true
  sectionKey?: true
  title?: true
  bodyText?: true
  ctaLabel?: true
  ctaHref?: true
  ctaSecondaryLabel?: true
  ctaSecondaryHref?: true
  imageUrl?: true
  sortOrder?: true
  isPublished?: true
  updatedByAdminId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PageContentBlockAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PageContentBlock to aggregate.
   */
  where?: Prisma.PageContentBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageContentBlocks to fetch.
   */
  orderBy?: Prisma.PageContentBlockOrderByWithRelationInput | Prisma.PageContentBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PageContentBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageContentBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageContentBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PageContentBlocks
  **/
  _count?: true | PageContentBlockCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PageContentBlockAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PageContentBlockSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PageContentBlockMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PageContentBlockMaxAggregateInputType
}

export type GetPageContentBlockAggregateType<T extends PageContentBlockAggregateArgs> = {
      [P in keyof T & keyof AggregatePageContentBlock]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePageContentBlock[P]>
    : Prisma.GetScalarType<T[P], AggregatePageContentBlock[P]>
}




export type PageContentBlockGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PageContentBlockWhereInput
  orderBy?: Prisma.PageContentBlockOrderByWithAggregationInput | Prisma.PageContentBlockOrderByWithAggregationInput[]
  by: Prisma.PageContentBlockScalarFieldEnum[] | Prisma.PageContentBlockScalarFieldEnum
  having?: Prisma.PageContentBlockScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PageContentBlockCountAggregateInputType | true
  _avg?: PageContentBlockAvgAggregateInputType
  _sum?: PageContentBlockSumAggregateInputType
  _min?: PageContentBlockMinAggregateInputType
  _max?: PageContentBlockMaxAggregateInputType
}

export type PageContentBlockGroupByOutputType = {
  id: string
  pageKey: string
  sectionKey: string
  title: string | null
  bodyText: string | null
  ctaLabel: string | null
  ctaHref: string | null
  ctaSecondaryLabel: string | null
  ctaSecondaryHref: string | null
  imageUrl: string | null
  sortOrder: number
  isPublished: boolean
  updatedByAdminId: string | null
  createdAt: Date
  updatedAt: Date
  _count: PageContentBlockCountAggregateOutputType | null
  _avg: PageContentBlockAvgAggregateOutputType | null
  _sum: PageContentBlockSumAggregateOutputType | null
  _min: PageContentBlockMinAggregateOutputType | null
  _max: PageContentBlockMaxAggregateOutputType | null
}

type GetPageContentBlockGroupByPayload<T extends PageContentBlockGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PageContentBlockGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PageContentBlockGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PageContentBlockGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PageContentBlockGroupByOutputType[P]>
      }
    >
  >



export type PageContentBlockWhereInput = {
  AND?: Prisma.PageContentBlockWhereInput | Prisma.PageContentBlockWhereInput[]
  OR?: Prisma.PageContentBlockWhereInput[]
  NOT?: Prisma.PageContentBlockWhereInput | Prisma.PageContentBlockWhereInput[]
  id?: Prisma.StringFilter<"PageContentBlock"> | string
  pageKey?: Prisma.StringFilter<"PageContentBlock"> | string
  sectionKey?: Prisma.StringFilter<"PageContentBlock"> | string
  title?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  bodyText?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  ctaLabel?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  ctaHref?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  ctaSecondaryLabel?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  ctaSecondaryHref?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  imageUrl?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  sortOrder?: Prisma.IntFilter<"PageContentBlock"> | number
  isPublished?: Prisma.BoolFilter<"PageContentBlock"> | boolean
  updatedByAdminId?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PageContentBlock"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PageContentBlock"> | Date | string
  updatedByAdmin?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type PageContentBlockOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pageKey?: Prisma.SortOrder
  sectionKey?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  bodyText?: Prisma.SortOrderInput | Prisma.SortOrder
  ctaLabel?: Prisma.SortOrderInput | Prisma.SortOrder
  ctaHref?: Prisma.SortOrderInput | Prisma.SortOrder
  ctaSecondaryLabel?: Prisma.SortOrderInput | Prisma.SortOrder
  ctaSecondaryHref?: Prisma.SortOrderInput | Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  updatedByAdminId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  updatedByAdmin?: Prisma.UserOrderByWithRelationInput
}

export type PageContentBlockWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PageContentBlockWhereInput | Prisma.PageContentBlockWhereInput[]
  OR?: Prisma.PageContentBlockWhereInput[]
  NOT?: Prisma.PageContentBlockWhereInput | Prisma.PageContentBlockWhereInput[]
  pageKey?: Prisma.StringFilter<"PageContentBlock"> | string
  sectionKey?: Prisma.StringFilter<"PageContentBlock"> | string
  title?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  bodyText?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  ctaLabel?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  ctaHref?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  ctaSecondaryLabel?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  ctaSecondaryHref?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  imageUrl?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  sortOrder?: Prisma.IntFilter<"PageContentBlock"> | number
  isPublished?: Prisma.BoolFilter<"PageContentBlock"> | boolean
  updatedByAdminId?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PageContentBlock"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PageContentBlock"> | Date | string
  updatedByAdmin?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type PageContentBlockOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pageKey?: Prisma.SortOrder
  sectionKey?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  bodyText?: Prisma.SortOrderInput | Prisma.SortOrder
  ctaLabel?: Prisma.SortOrderInput | Prisma.SortOrder
  ctaHref?: Prisma.SortOrderInput | Prisma.SortOrder
  ctaSecondaryLabel?: Prisma.SortOrderInput | Prisma.SortOrder
  ctaSecondaryHref?: Prisma.SortOrderInput | Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  updatedByAdminId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PageContentBlockCountOrderByAggregateInput
  _avg?: Prisma.PageContentBlockAvgOrderByAggregateInput
  _max?: Prisma.PageContentBlockMaxOrderByAggregateInput
  _min?: Prisma.PageContentBlockMinOrderByAggregateInput
  _sum?: Prisma.PageContentBlockSumOrderByAggregateInput
}

export type PageContentBlockScalarWhereWithAggregatesInput = {
  AND?: Prisma.PageContentBlockScalarWhereWithAggregatesInput | Prisma.PageContentBlockScalarWhereWithAggregatesInput[]
  OR?: Prisma.PageContentBlockScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PageContentBlockScalarWhereWithAggregatesInput | Prisma.PageContentBlockScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PageContentBlock"> | string
  pageKey?: Prisma.StringWithAggregatesFilter<"PageContentBlock"> | string
  sectionKey?: Prisma.StringWithAggregatesFilter<"PageContentBlock"> | string
  title?: Prisma.StringNullableWithAggregatesFilter<"PageContentBlock"> | string | null
  bodyText?: Prisma.StringNullableWithAggregatesFilter<"PageContentBlock"> | string | null
  ctaLabel?: Prisma.StringNullableWithAggregatesFilter<"PageContentBlock"> | string | null
  ctaHref?: Prisma.StringNullableWithAggregatesFilter<"PageContentBlock"> | string | null
  ctaSecondaryLabel?: Prisma.StringNullableWithAggregatesFilter<"PageContentBlock"> | string | null
  ctaSecondaryHref?: Prisma.StringNullableWithAggregatesFilter<"PageContentBlock"> | string | null
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"PageContentBlock"> | string | null
  sortOrder?: Prisma.IntWithAggregatesFilter<"PageContentBlock"> | number
  isPublished?: Prisma.BoolWithAggregatesFilter<"PageContentBlock"> | boolean
  updatedByAdminId?: Prisma.StringNullableWithAggregatesFilter<"PageContentBlock"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PageContentBlock"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PageContentBlock"> | Date | string
}

export type PageContentBlockCreateInput = {
  id?: string
  pageKey: string
  sectionKey: string
  title?: string | null
  bodyText?: string | null
  ctaLabel?: string | null
  ctaHref?: string | null
  ctaSecondaryLabel?: string | null
  ctaSecondaryHref?: string | null
  imageUrl?: string | null
  sortOrder?: number
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  updatedByAdmin?: Prisma.UserCreateNestedOneWithoutUpdatedPageContentBlocksInput
}

export type PageContentBlockUncheckedCreateInput = {
  id?: string
  pageKey: string
  sectionKey: string
  title?: string | null
  bodyText?: string | null
  ctaLabel?: string | null
  ctaHref?: string | null
  ctaSecondaryLabel?: string | null
  ctaSecondaryHref?: string | null
  imageUrl?: string | null
  sortOrder?: number
  isPublished?: boolean
  updatedByAdminId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PageContentBlockUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageKey?: Prisma.StringFieldUpdateOperationsInput | string
  sectionKey?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedByAdmin?: Prisma.UserUpdateOneWithoutUpdatedPageContentBlocksNestedInput
}

export type PageContentBlockUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageKey?: Prisma.StringFieldUpdateOperationsInput | string
  sectionKey?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedByAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PageContentBlockCreateManyInput = {
  id?: string
  pageKey: string
  sectionKey: string
  title?: string | null
  bodyText?: string | null
  ctaLabel?: string | null
  ctaHref?: string | null
  ctaSecondaryLabel?: string | null
  ctaSecondaryHref?: string | null
  imageUrl?: string | null
  sortOrder?: number
  isPublished?: boolean
  updatedByAdminId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PageContentBlockUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageKey?: Prisma.StringFieldUpdateOperationsInput | string
  sectionKey?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PageContentBlockUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageKey?: Prisma.StringFieldUpdateOperationsInput | string
  sectionKey?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedByAdminId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PageContentBlockListRelationFilter = {
  every?: Prisma.PageContentBlockWhereInput
  some?: Prisma.PageContentBlockWhereInput
  none?: Prisma.PageContentBlockWhereInput
}

export type PageContentBlockOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PageContentBlockCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pageKey?: Prisma.SortOrder
  sectionKey?: Prisma.SortOrder
  title?: Prisma.SortOrder
  bodyText?: Prisma.SortOrder
  ctaLabel?: Prisma.SortOrder
  ctaHref?: Prisma.SortOrder
  ctaSecondaryLabel?: Prisma.SortOrder
  ctaSecondaryHref?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  updatedByAdminId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PageContentBlockAvgOrderByAggregateInput = {
  sortOrder?: Prisma.SortOrder
}

export type PageContentBlockMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pageKey?: Prisma.SortOrder
  sectionKey?: Prisma.SortOrder
  title?: Prisma.SortOrder
  bodyText?: Prisma.SortOrder
  ctaLabel?: Prisma.SortOrder
  ctaHref?: Prisma.SortOrder
  ctaSecondaryLabel?: Prisma.SortOrder
  ctaSecondaryHref?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  updatedByAdminId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PageContentBlockMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pageKey?: Prisma.SortOrder
  sectionKey?: Prisma.SortOrder
  title?: Prisma.SortOrder
  bodyText?: Prisma.SortOrder
  ctaLabel?: Prisma.SortOrder
  ctaHref?: Prisma.SortOrder
  ctaSecondaryLabel?: Prisma.SortOrder
  ctaSecondaryHref?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  updatedByAdminId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PageContentBlockSumOrderByAggregateInput = {
  sortOrder?: Prisma.SortOrder
}

export type PageContentBlockCreateNestedManyWithoutUpdatedByAdminInput = {
  create?: Prisma.XOR<Prisma.PageContentBlockCreateWithoutUpdatedByAdminInput, Prisma.PageContentBlockUncheckedCreateWithoutUpdatedByAdminInput> | Prisma.PageContentBlockCreateWithoutUpdatedByAdminInput[] | Prisma.PageContentBlockUncheckedCreateWithoutUpdatedByAdminInput[]
  connectOrCreate?: Prisma.PageContentBlockCreateOrConnectWithoutUpdatedByAdminInput | Prisma.PageContentBlockCreateOrConnectWithoutUpdatedByAdminInput[]
  createMany?: Prisma.PageContentBlockCreateManyUpdatedByAdminInputEnvelope
  connect?: Prisma.PageContentBlockWhereUniqueInput | Prisma.PageContentBlockWhereUniqueInput[]
}

export type PageContentBlockUncheckedCreateNestedManyWithoutUpdatedByAdminInput = {
  create?: Prisma.XOR<Prisma.PageContentBlockCreateWithoutUpdatedByAdminInput, Prisma.PageContentBlockUncheckedCreateWithoutUpdatedByAdminInput> | Prisma.PageContentBlockCreateWithoutUpdatedByAdminInput[] | Prisma.PageContentBlockUncheckedCreateWithoutUpdatedByAdminInput[]
  connectOrCreate?: Prisma.PageContentBlockCreateOrConnectWithoutUpdatedByAdminInput | Prisma.PageContentBlockCreateOrConnectWithoutUpdatedByAdminInput[]
  createMany?: Prisma.PageContentBlockCreateManyUpdatedByAdminInputEnvelope
  connect?: Prisma.PageContentBlockWhereUniqueInput | Prisma.PageContentBlockWhereUniqueInput[]
}

export type PageContentBlockUpdateManyWithoutUpdatedByAdminNestedInput = {
  create?: Prisma.XOR<Prisma.PageContentBlockCreateWithoutUpdatedByAdminInput, Prisma.PageContentBlockUncheckedCreateWithoutUpdatedByAdminInput> | Prisma.PageContentBlockCreateWithoutUpdatedByAdminInput[] | Prisma.PageContentBlockUncheckedCreateWithoutUpdatedByAdminInput[]
  connectOrCreate?: Prisma.PageContentBlockCreateOrConnectWithoutUpdatedByAdminInput | Prisma.PageContentBlockCreateOrConnectWithoutUpdatedByAdminInput[]
  upsert?: Prisma.PageContentBlockUpsertWithWhereUniqueWithoutUpdatedByAdminInput | Prisma.PageContentBlockUpsertWithWhereUniqueWithoutUpdatedByAdminInput[]
  createMany?: Prisma.PageContentBlockCreateManyUpdatedByAdminInputEnvelope
  set?: Prisma.PageContentBlockWhereUniqueInput | Prisma.PageContentBlockWhereUniqueInput[]
  disconnect?: Prisma.PageContentBlockWhereUniqueInput | Prisma.PageContentBlockWhereUniqueInput[]
  delete?: Prisma.PageContentBlockWhereUniqueInput | Prisma.PageContentBlockWhereUniqueInput[]
  connect?: Prisma.PageContentBlockWhereUniqueInput | Prisma.PageContentBlockWhereUniqueInput[]
  update?: Prisma.PageContentBlockUpdateWithWhereUniqueWithoutUpdatedByAdminInput | Prisma.PageContentBlockUpdateWithWhereUniqueWithoutUpdatedByAdminInput[]
  updateMany?: Prisma.PageContentBlockUpdateManyWithWhereWithoutUpdatedByAdminInput | Prisma.PageContentBlockUpdateManyWithWhereWithoutUpdatedByAdminInput[]
  deleteMany?: Prisma.PageContentBlockScalarWhereInput | Prisma.PageContentBlockScalarWhereInput[]
}

export type PageContentBlockUncheckedUpdateManyWithoutUpdatedByAdminNestedInput = {
  create?: Prisma.XOR<Prisma.PageContentBlockCreateWithoutUpdatedByAdminInput, Prisma.PageContentBlockUncheckedCreateWithoutUpdatedByAdminInput> | Prisma.PageContentBlockCreateWithoutUpdatedByAdminInput[] | Prisma.PageContentBlockUncheckedCreateWithoutUpdatedByAdminInput[]
  connectOrCreate?: Prisma.PageContentBlockCreateOrConnectWithoutUpdatedByAdminInput | Prisma.PageContentBlockCreateOrConnectWithoutUpdatedByAdminInput[]
  upsert?: Prisma.PageContentBlockUpsertWithWhereUniqueWithoutUpdatedByAdminInput | Prisma.PageContentBlockUpsertWithWhereUniqueWithoutUpdatedByAdminInput[]
  createMany?: Prisma.PageContentBlockCreateManyUpdatedByAdminInputEnvelope
  set?: Prisma.PageContentBlockWhereUniqueInput | Prisma.PageContentBlockWhereUniqueInput[]
  disconnect?: Prisma.PageContentBlockWhereUniqueInput | Prisma.PageContentBlockWhereUniqueInput[]
  delete?: Prisma.PageContentBlockWhereUniqueInput | Prisma.PageContentBlockWhereUniqueInput[]
  connect?: Prisma.PageContentBlockWhereUniqueInput | Prisma.PageContentBlockWhereUniqueInput[]
  update?: Prisma.PageContentBlockUpdateWithWhereUniqueWithoutUpdatedByAdminInput | Prisma.PageContentBlockUpdateWithWhereUniqueWithoutUpdatedByAdminInput[]
  updateMany?: Prisma.PageContentBlockUpdateManyWithWhereWithoutUpdatedByAdminInput | Prisma.PageContentBlockUpdateManyWithWhereWithoutUpdatedByAdminInput[]
  deleteMany?: Prisma.PageContentBlockScalarWhereInput | Prisma.PageContentBlockScalarWhereInput[]
}

export type PageContentBlockCreateWithoutUpdatedByAdminInput = {
  id?: string
  pageKey: string
  sectionKey: string
  title?: string | null
  bodyText?: string | null
  ctaLabel?: string | null
  ctaHref?: string | null
  ctaSecondaryLabel?: string | null
  ctaSecondaryHref?: string | null
  imageUrl?: string | null
  sortOrder?: number
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PageContentBlockUncheckedCreateWithoutUpdatedByAdminInput = {
  id?: string
  pageKey: string
  sectionKey: string
  title?: string | null
  bodyText?: string | null
  ctaLabel?: string | null
  ctaHref?: string | null
  ctaSecondaryLabel?: string | null
  ctaSecondaryHref?: string | null
  imageUrl?: string | null
  sortOrder?: number
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PageContentBlockCreateOrConnectWithoutUpdatedByAdminInput = {
  where: Prisma.PageContentBlockWhereUniqueInput
  create: Prisma.XOR<Prisma.PageContentBlockCreateWithoutUpdatedByAdminInput, Prisma.PageContentBlockUncheckedCreateWithoutUpdatedByAdminInput>
}

export type PageContentBlockCreateManyUpdatedByAdminInputEnvelope = {
  data: Prisma.PageContentBlockCreateManyUpdatedByAdminInput | Prisma.PageContentBlockCreateManyUpdatedByAdminInput[]
  skipDuplicates?: boolean
}

export type PageContentBlockUpsertWithWhereUniqueWithoutUpdatedByAdminInput = {
  where: Prisma.PageContentBlockWhereUniqueInput
  update: Prisma.XOR<Prisma.PageContentBlockUpdateWithoutUpdatedByAdminInput, Prisma.PageContentBlockUncheckedUpdateWithoutUpdatedByAdminInput>
  create: Prisma.XOR<Prisma.PageContentBlockCreateWithoutUpdatedByAdminInput, Prisma.PageContentBlockUncheckedCreateWithoutUpdatedByAdminInput>
}

export type PageContentBlockUpdateWithWhereUniqueWithoutUpdatedByAdminInput = {
  where: Prisma.PageContentBlockWhereUniqueInput
  data: Prisma.XOR<Prisma.PageContentBlockUpdateWithoutUpdatedByAdminInput, Prisma.PageContentBlockUncheckedUpdateWithoutUpdatedByAdminInput>
}

export type PageContentBlockUpdateManyWithWhereWithoutUpdatedByAdminInput = {
  where: Prisma.PageContentBlockScalarWhereInput
  data: Prisma.XOR<Prisma.PageContentBlockUpdateManyMutationInput, Prisma.PageContentBlockUncheckedUpdateManyWithoutUpdatedByAdminInput>
}

export type PageContentBlockScalarWhereInput = {
  AND?: Prisma.PageContentBlockScalarWhereInput | Prisma.PageContentBlockScalarWhereInput[]
  OR?: Prisma.PageContentBlockScalarWhereInput[]
  NOT?: Prisma.PageContentBlockScalarWhereInput | Prisma.PageContentBlockScalarWhereInput[]
  id?: Prisma.StringFilter<"PageContentBlock"> | string
  pageKey?: Prisma.StringFilter<"PageContentBlock"> | string
  sectionKey?: Prisma.StringFilter<"PageContentBlock"> | string
  title?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  bodyText?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  ctaLabel?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  ctaHref?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  ctaSecondaryLabel?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  ctaSecondaryHref?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  imageUrl?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  sortOrder?: Prisma.IntFilter<"PageContentBlock"> | number
  isPublished?: Prisma.BoolFilter<"PageContentBlock"> | boolean
  updatedByAdminId?: Prisma.StringNullableFilter<"PageContentBlock"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PageContentBlock"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PageContentBlock"> | Date | string
}

export type PageContentBlockCreateManyUpdatedByAdminInput = {
  id?: string
  pageKey: string
  sectionKey: string
  title?: string | null
  bodyText?: string | null
  ctaLabel?: string | null
  ctaHref?: string | null
  ctaSecondaryLabel?: string | null
  ctaSecondaryHref?: string | null
  imageUrl?: string | null
  sortOrder?: number
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PageContentBlockUpdateWithoutUpdatedByAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageKey?: Prisma.StringFieldUpdateOperationsInput | string
  sectionKey?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PageContentBlockUncheckedUpdateWithoutUpdatedByAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageKey?: Prisma.StringFieldUpdateOperationsInput | string
  sectionKey?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PageContentBlockUncheckedUpdateManyWithoutUpdatedByAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageKey?: Prisma.StringFieldUpdateOperationsInput | string
  sectionKey?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ctaSecondaryHref?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PageContentBlockSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pageKey?: boolean
  sectionKey?: boolean
  title?: boolean
  bodyText?: boolean
  ctaLabel?: boolean
  ctaHref?: boolean
  ctaSecondaryLabel?: boolean
  ctaSecondaryHref?: boolean
  imageUrl?: boolean
  sortOrder?: boolean
  isPublished?: boolean
  updatedByAdminId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  updatedByAdmin?: boolean | Prisma.PageContentBlock$updatedByAdminArgs<ExtArgs>
}, ExtArgs["result"]["pageContentBlock"]>

export type PageContentBlockSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pageKey?: boolean
  sectionKey?: boolean
  title?: boolean
  bodyText?: boolean
  ctaLabel?: boolean
  ctaHref?: boolean
  ctaSecondaryLabel?: boolean
  ctaSecondaryHref?: boolean
  imageUrl?: boolean
  sortOrder?: boolean
  isPublished?: boolean
  updatedByAdminId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  updatedByAdmin?: boolean | Prisma.PageContentBlock$updatedByAdminArgs<ExtArgs>
}, ExtArgs["result"]["pageContentBlock"]>

export type PageContentBlockSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pageKey?: boolean
  sectionKey?: boolean
  title?: boolean
  bodyText?: boolean
  ctaLabel?: boolean
  ctaHref?: boolean
  ctaSecondaryLabel?: boolean
  ctaSecondaryHref?: boolean
  imageUrl?: boolean
  sortOrder?: boolean
  isPublished?: boolean
  updatedByAdminId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  updatedByAdmin?: boolean | Prisma.PageContentBlock$updatedByAdminArgs<ExtArgs>
}, ExtArgs["result"]["pageContentBlock"]>

export type PageContentBlockSelectScalar = {
  id?: boolean
  pageKey?: boolean
  sectionKey?: boolean
  title?: boolean
  bodyText?: boolean
  ctaLabel?: boolean
  ctaHref?: boolean
  ctaSecondaryLabel?: boolean
  ctaSecondaryHref?: boolean
  imageUrl?: boolean
  sortOrder?: boolean
  isPublished?: boolean
  updatedByAdminId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PageContentBlockOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pageKey" | "sectionKey" | "title" | "bodyText" | "ctaLabel" | "ctaHref" | "ctaSecondaryLabel" | "ctaSecondaryHref" | "imageUrl" | "sortOrder" | "isPublished" | "updatedByAdminId" | "createdAt" | "updatedAt", ExtArgs["result"]["pageContentBlock"]>
export type PageContentBlockInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  updatedByAdmin?: boolean | Prisma.PageContentBlock$updatedByAdminArgs<ExtArgs>
}
export type PageContentBlockIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  updatedByAdmin?: boolean | Prisma.PageContentBlock$updatedByAdminArgs<ExtArgs>
}
export type PageContentBlockIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  updatedByAdmin?: boolean | Prisma.PageContentBlock$updatedByAdminArgs<ExtArgs>
}

export type $PageContentBlockPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PageContentBlock"
  objects: {
    updatedByAdmin: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    pageKey: string
    sectionKey: string
    title: string | null
    bodyText: string | null
    ctaLabel: string | null
    ctaHref: string | null
    ctaSecondaryLabel: string | null
    ctaSecondaryHref: string | null
    imageUrl: string | null
    sortOrder: number
    isPublished: boolean
    updatedByAdminId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["pageContentBlock"]>
  composites: {}
}

export type PageContentBlockGetPayload<S extends boolean | null | undefined | PageContentBlockDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PageContentBlockPayload, S>

export type PageContentBlockCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PageContentBlockFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PageContentBlockCountAggregateInputType | true
  }

export interface PageContentBlockDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PageContentBlock'], meta: { name: 'PageContentBlock' } }
  /**
   * Find zero or one PageContentBlock that matches the filter.
   * @param {PageContentBlockFindUniqueArgs} args - Arguments to find a PageContentBlock
   * @example
   * // Get one PageContentBlock
   * const pageContentBlock = await prisma.pageContentBlock.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PageContentBlockFindUniqueArgs>(args: Prisma.SelectSubset<T, PageContentBlockFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PageContentBlockClient<runtime.Types.Result.GetResult<Prisma.$PageContentBlockPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PageContentBlock that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PageContentBlockFindUniqueOrThrowArgs} args - Arguments to find a PageContentBlock
   * @example
   * // Get one PageContentBlock
   * const pageContentBlock = await prisma.pageContentBlock.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PageContentBlockFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PageContentBlockFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PageContentBlockClient<runtime.Types.Result.GetResult<Prisma.$PageContentBlockPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PageContentBlock that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageContentBlockFindFirstArgs} args - Arguments to find a PageContentBlock
   * @example
   * // Get one PageContentBlock
   * const pageContentBlock = await prisma.pageContentBlock.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PageContentBlockFindFirstArgs>(args?: Prisma.SelectSubset<T, PageContentBlockFindFirstArgs<ExtArgs>>): Prisma.Prisma__PageContentBlockClient<runtime.Types.Result.GetResult<Prisma.$PageContentBlockPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PageContentBlock that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageContentBlockFindFirstOrThrowArgs} args - Arguments to find a PageContentBlock
   * @example
   * // Get one PageContentBlock
   * const pageContentBlock = await prisma.pageContentBlock.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PageContentBlockFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PageContentBlockFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PageContentBlockClient<runtime.Types.Result.GetResult<Prisma.$PageContentBlockPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PageContentBlocks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageContentBlockFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PageContentBlocks
   * const pageContentBlocks = await prisma.pageContentBlock.findMany()
   * 
   * // Get first 10 PageContentBlocks
   * const pageContentBlocks = await prisma.pageContentBlock.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pageContentBlockWithIdOnly = await prisma.pageContentBlock.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PageContentBlockFindManyArgs>(args?: Prisma.SelectSubset<T, PageContentBlockFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PageContentBlockPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PageContentBlock.
   * @param {PageContentBlockCreateArgs} args - Arguments to create a PageContentBlock.
   * @example
   * // Create one PageContentBlock
   * const PageContentBlock = await prisma.pageContentBlock.create({
   *   data: {
   *     // ... data to create a PageContentBlock
   *   }
   * })
   * 
   */
  create<T extends PageContentBlockCreateArgs>(args: Prisma.SelectSubset<T, PageContentBlockCreateArgs<ExtArgs>>): Prisma.Prisma__PageContentBlockClient<runtime.Types.Result.GetResult<Prisma.$PageContentBlockPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PageContentBlocks.
   * @param {PageContentBlockCreateManyArgs} args - Arguments to create many PageContentBlocks.
   * @example
   * // Create many PageContentBlocks
   * const pageContentBlock = await prisma.pageContentBlock.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PageContentBlockCreateManyArgs>(args?: Prisma.SelectSubset<T, PageContentBlockCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PageContentBlocks and returns the data saved in the database.
   * @param {PageContentBlockCreateManyAndReturnArgs} args - Arguments to create many PageContentBlocks.
   * @example
   * // Create many PageContentBlocks
   * const pageContentBlock = await prisma.pageContentBlock.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PageContentBlocks and only return the `id`
   * const pageContentBlockWithIdOnly = await prisma.pageContentBlock.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PageContentBlockCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PageContentBlockCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PageContentBlockPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PageContentBlock.
   * @param {PageContentBlockDeleteArgs} args - Arguments to delete one PageContentBlock.
   * @example
   * // Delete one PageContentBlock
   * const PageContentBlock = await prisma.pageContentBlock.delete({
   *   where: {
   *     // ... filter to delete one PageContentBlock
   *   }
   * })
   * 
   */
  delete<T extends PageContentBlockDeleteArgs>(args: Prisma.SelectSubset<T, PageContentBlockDeleteArgs<ExtArgs>>): Prisma.Prisma__PageContentBlockClient<runtime.Types.Result.GetResult<Prisma.$PageContentBlockPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PageContentBlock.
   * @param {PageContentBlockUpdateArgs} args - Arguments to update one PageContentBlock.
   * @example
   * // Update one PageContentBlock
   * const pageContentBlock = await prisma.pageContentBlock.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PageContentBlockUpdateArgs>(args: Prisma.SelectSubset<T, PageContentBlockUpdateArgs<ExtArgs>>): Prisma.Prisma__PageContentBlockClient<runtime.Types.Result.GetResult<Prisma.$PageContentBlockPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PageContentBlocks.
   * @param {PageContentBlockDeleteManyArgs} args - Arguments to filter PageContentBlocks to delete.
   * @example
   * // Delete a few PageContentBlocks
   * const { count } = await prisma.pageContentBlock.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PageContentBlockDeleteManyArgs>(args?: Prisma.SelectSubset<T, PageContentBlockDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PageContentBlocks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageContentBlockUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PageContentBlocks
   * const pageContentBlock = await prisma.pageContentBlock.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PageContentBlockUpdateManyArgs>(args: Prisma.SelectSubset<T, PageContentBlockUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PageContentBlocks and returns the data updated in the database.
   * @param {PageContentBlockUpdateManyAndReturnArgs} args - Arguments to update many PageContentBlocks.
   * @example
   * // Update many PageContentBlocks
   * const pageContentBlock = await prisma.pageContentBlock.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PageContentBlocks and only return the `id`
   * const pageContentBlockWithIdOnly = await prisma.pageContentBlock.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PageContentBlockUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PageContentBlockUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PageContentBlockPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PageContentBlock.
   * @param {PageContentBlockUpsertArgs} args - Arguments to update or create a PageContentBlock.
   * @example
   * // Update or create a PageContentBlock
   * const pageContentBlock = await prisma.pageContentBlock.upsert({
   *   create: {
   *     // ... data to create a PageContentBlock
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PageContentBlock we want to update
   *   }
   * })
   */
  upsert<T extends PageContentBlockUpsertArgs>(args: Prisma.SelectSubset<T, PageContentBlockUpsertArgs<ExtArgs>>): Prisma.Prisma__PageContentBlockClient<runtime.Types.Result.GetResult<Prisma.$PageContentBlockPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PageContentBlocks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageContentBlockCountArgs} args - Arguments to filter PageContentBlocks to count.
   * @example
   * // Count the number of PageContentBlocks
   * const count = await prisma.pageContentBlock.count({
   *   where: {
   *     // ... the filter for the PageContentBlocks we want to count
   *   }
   * })
  **/
  count<T extends PageContentBlockCountArgs>(
    args?: Prisma.Subset<T, PageContentBlockCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PageContentBlockCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PageContentBlock.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageContentBlockAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PageContentBlockAggregateArgs>(args: Prisma.Subset<T, PageContentBlockAggregateArgs>): Prisma.PrismaPromise<GetPageContentBlockAggregateType<T>>

  /**
   * Group by PageContentBlock.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageContentBlockGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PageContentBlockGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PageContentBlockGroupByArgs['orderBy'] }
      : { orderBy?: PageContentBlockGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PageContentBlockGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPageContentBlockGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PageContentBlock model
 */
readonly fields: PageContentBlockFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PageContentBlock.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PageContentBlockClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  updatedByAdmin<T extends Prisma.PageContentBlock$updatedByAdminArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PageContentBlock$updatedByAdminArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PageContentBlock model
 */
export interface PageContentBlockFieldRefs {
  readonly id: Prisma.FieldRef<"PageContentBlock", 'String'>
  readonly pageKey: Prisma.FieldRef<"PageContentBlock", 'String'>
  readonly sectionKey: Prisma.FieldRef<"PageContentBlock", 'String'>
  readonly title: Prisma.FieldRef<"PageContentBlock", 'String'>
  readonly bodyText: Prisma.FieldRef<"PageContentBlock", 'String'>
  readonly ctaLabel: Prisma.FieldRef<"PageContentBlock", 'String'>
  readonly ctaHref: Prisma.FieldRef<"PageContentBlock", 'String'>
  readonly ctaSecondaryLabel: Prisma.FieldRef<"PageContentBlock", 'String'>
  readonly ctaSecondaryHref: Prisma.FieldRef<"PageContentBlock", 'String'>
  readonly imageUrl: Prisma.FieldRef<"PageContentBlock", 'String'>
  readonly sortOrder: Prisma.FieldRef<"PageContentBlock", 'Int'>
  readonly isPublished: Prisma.FieldRef<"PageContentBlock", 'Boolean'>
  readonly updatedByAdminId: Prisma.FieldRef<"PageContentBlock", 'String'>
  readonly createdAt: Prisma.FieldRef<"PageContentBlock", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PageContentBlock", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PageContentBlock findUnique
 */
export type PageContentBlockFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageContentBlock
   */
  select?: Prisma.PageContentBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageContentBlock
   */
  omit?: Prisma.PageContentBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageContentBlockInclude<ExtArgs> | null
  /**
   * Filter, which PageContentBlock to fetch.
   */
  where: Prisma.PageContentBlockWhereUniqueInput
}

/**
 * PageContentBlock findUniqueOrThrow
 */
export type PageContentBlockFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageContentBlock
   */
  select?: Prisma.PageContentBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageContentBlock
   */
  omit?: Prisma.PageContentBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageContentBlockInclude<ExtArgs> | null
  /**
   * Filter, which PageContentBlock to fetch.
   */
  where: Prisma.PageContentBlockWhereUniqueInput
}

/**
 * PageContentBlock findFirst
 */
export type PageContentBlockFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageContentBlock
   */
  select?: Prisma.PageContentBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageContentBlock
   */
  omit?: Prisma.PageContentBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageContentBlockInclude<ExtArgs> | null
  /**
   * Filter, which PageContentBlock to fetch.
   */
  where?: Prisma.PageContentBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageContentBlocks to fetch.
   */
  orderBy?: Prisma.PageContentBlockOrderByWithRelationInput | Prisma.PageContentBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PageContentBlocks.
   */
  cursor?: Prisma.PageContentBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageContentBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageContentBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PageContentBlocks.
   */
  distinct?: Prisma.PageContentBlockScalarFieldEnum | Prisma.PageContentBlockScalarFieldEnum[]
}

/**
 * PageContentBlock findFirstOrThrow
 */
export type PageContentBlockFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageContentBlock
   */
  select?: Prisma.PageContentBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageContentBlock
   */
  omit?: Prisma.PageContentBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageContentBlockInclude<ExtArgs> | null
  /**
   * Filter, which PageContentBlock to fetch.
   */
  where?: Prisma.PageContentBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageContentBlocks to fetch.
   */
  orderBy?: Prisma.PageContentBlockOrderByWithRelationInput | Prisma.PageContentBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PageContentBlocks.
   */
  cursor?: Prisma.PageContentBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageContentBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageContentBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PageContentBlocks.
   */
  distinct?: Prisma.PageContentBlockScalarFieldEnum | Prisma.PageContentBlockScalarFieldEnum[]
}

/**
 * PageContentBlock findMany
 */
export type PageContentBlockFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageContentBlock
   */
  select?: Prisma.PageContentBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageContentBlock
   */
  omit?: Prisma.PageContentBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageContentBlockInclude<ExtArgs> | null
  /**
   * Filter, which PageContentBlocks to fetch.
   */
  where?: Prisma.PageContentBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageContentBlocks to fetch.
   */
  orderBy?: Prisma.PageContentBlockOrderByWithRelationInput | Prisma.PageContentBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PageContentBlocks.
   */
  cursor?: Prisma.PageContentBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageContentBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageContentBlocks.
   */
  skip?: number
  distinct?: Prisma.PageContentBlockScalarFieldEnum | Prisma.PageContentBlockScalarFieldEnum[]
}

/**
 * PageContentBlock create
 */
export type PageContentBlockCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageContentBlock
   */
  select?: Prisma.PageContentBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageContentBlock
   */
  omit?: Prisma.PageContentBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageContentBlockInclude<ExtArgs> | null
  /**
   * The data needed to create a PageContentBlock.
   */
  data: Prisma.XOR<Prisma.PageContentBlockCreateInput, Prisma.PageContentBlockUncheckedCreateInput>
}

/**
 * PageContentBlock createMany
 */
export type PageContentBlockCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PageContentBlocks.
   */
  data: Prisma.PageContentBlockCreateManyInput | Prisma.PageContentBlockCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PageContentBlock createManyAndReturn
 */
export type PageContentBlockCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageContentBlock
   */
  select?: Prisma.PageContentBlockSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PageContentBlock
   */
  omit?: Prisma.PageContentBlockOmit<ExtArgs> | null
  /**
   * The data used to create many PageContentBlocks.
   */
  data: Prisma.PageContentBlockCreateManyInput | Prisma.PageContentBlockCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageContentBlockIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PageContentBlock update
 */
export type PageContentBlockUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageContentBlock
   */
  select?: Prisma.PageContentBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageContentBlock
   */
  omit?: Prisma.PageContentBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageContentBlockInclude<ExtArgs> | null
  /**
   * The data needed to update a PageContentBlock.
   */
  data: Prisma.XOR<Prisma.PageContentBlockUpdateInput, Prisma.PageContentBlockUncheckedUpdateInput>
  /**
   * Choose, which PageContentBlock to update.
   */
  where: Prisma.PageContentBlockWhereUniqueInput
}

/**
 * PageContentBlock updateMany
 */
export type PageContentBlockUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PageContentBlocks.
   */
  data: Prisma.XOR<Prisma.PageContentBlockUpdateManyMutationInput, Prisma.PageContentBlockUncheckedUpdateManyInput>
  /**
   * Filter which PageContentBlocks to update
   */
  where?: Prisma.PageContentBlockWhereInput
  /**
   * Limit how many PageContentBlocks to update.
   */
  limit?: number
}

/**
 * PageContentBlock updateManyAndReturn
 */
export type PageContentBlockUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageContentBlock
   */
  select?: Prisma.PageContentBlockSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PageContentBlock
   */
  omit?: Prisma.PageContentBlockOmit<ExtArgs> | null
  /**
   * The data used to update PageContentBlocks.
   */
  data: Prisma.XOR<Prisma.PageContentBlockUpdateManyMutationInput, Prisma.PageContentBlockUncheckedUpdateManyInput>
  /**
   * Filter which PageContentBlocks to update
   */
  where?: Prisma.PageContentBlockWhereInput
  /**
   * Limit how many PageContentBlocks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageContentBlockIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PageContentBlock upsert
 */
export type PageContentBlockUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageContentBlock
   */
  select?: Prisma.PageContentBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageContentBlock
   */
  omit?: Prisma.PageContentBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageContentBlockInclude<ExtArgs> | null
  /**
   * The filter to search for the PageContentBlock to update in case it exists.
   */
  where: Prisma.PageContentBlockWhereUniqueInput
  /**
   * In case the PageContentBlock found by the `where` argument doesn't exist, create a new PageContentBlock with this data.
   */
  create: Prisma.XOR<Prisma.PageContentBlockCreateInput, Prisma.PageContentBlockUncheckedCreateInput>
  /**
   * In case the PageContentBlock was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PageContentBlockUpdateInput, Prisma.PageContentBlockUncheckedUpdateInput>
}

/**
 * PageContentBlock delete
 */
export type PageContentBlockDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageContentBlock
   */
  select?: Prisma.PageContentBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageContentBlock
   */
  omit?: Prisma.PageContentBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageContentBlockInclude<ExtArgs> | null
  /**
   * Filter which PageContentBlock to delete.
   */
  where: Prisma.PageContentBlockWhereUniqueInput
}

/**
 * PageContentBlock deleteMany
 */
export type PageContentBlockDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PageContentBlocks to delete
   */
  where?: Prisma.PageContentBlockWhereInput
  /**
   * Limit how many PageContentBlocks to delete.
   */
  limit?: number
}

/**
 * PageContentBlock.updatedByAdmin
 */
export type PageContentBlock$updatedByAdminArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * PageContentBlock without action
 */
export type PageContentBlockDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageContentBlock
   */
  select?: Prisma.PageContentBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageContentBlock
   */
  omit?: Prisma.PageContentBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageContentBlockInclude<ExtArgs> | null
}
