
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  House: 'House',
  Class: 'Class',
  Subscription: 'Subscription',
  Upload: 'Upload',
  Graduation: 'Graduation',
  StickerCatalog: 'StickerCatalog',
  GiftCatalog: 'GiftCatalog',
  Entitlement: 'Entitlement',
  Bundle: 'Bundle',
  ChatBundlePricing: 'ChatBundlePricing',
  Stream: 'Stream',
  StreamRecording: 'StreamRecording',
  RecordingDownloadAudit: 'RecordingDownloadAudit',
  ChatMessage: 'ChatMessage',
  Transaction: 'Transaction',
  Like: 'Like',
  FeaturedSlot: 'FeaturedSlot',
  AdminTask: 'AdminTask',
  AccountGrant: 'AccountGrant',
  CustomGroupOrder: 'CustomGroupOrder',
  CustomGroupSeat: 'CustomGroupSeat',
  PaymentWebhookEvent: 'PaymentWebhookEvent',
  DeviceSession: 'DeviceSession',
  TrialAttendance: 'TrialAttendance',
  PageContentBlock: 'PageContentBlock'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  role: 'role',
  nickname: 'nickname',
  avatarUrl: 'avatarUrl',
  age: 'age',
  country: 'country',
  favoriteColor: 'favoriteColor',
  strengthAnswer: 'strengthAnswer',
  allowGradVisible: 'allowGradVisible',
  trialAttendedCount: 'trialAttendedCount',
  bannedAt: 'bannedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const HouseScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type HouseScalarFieldEnum = (typeof HouseScalarFieldEnum)[keyof typeof HouseScalarFieldEnum]


export const ClassScalarFieldEnum = {
  id: 'id',
  houseId: 'houseId',
  level: 'level',
  teacherId: 'teacherId',
  dayPattern: 'dayPattern',
  time: 'time',
  timezone: 'timezone',
  lessonMinutes: 'lessonMinutes',
  qnaMinutes: 'qnaMinutes',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClassScalarFieldEnum = (typeof ClassScalarFieldEnum)[keyof typeof ClassScalarFieldEnum]


export const SubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  status: 'status',
  tierPriceCents: 'tierPriceCents',
  classId: 'classId',
  billingAnchor: 'billingAnchor',
  renewalDate: 'renewalDate',
  switchUsedThisCycle: 'switchUsedThisCycle',
  planCode: 'planCode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubscriptionScalarFieldEnum = (typeof SubscriptionScalarFieldEnum)[keyof typeof SubscriptionScalarFieldEnum]


export const UploadScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  subscriptionId: 'subscriptionId',
  classId: 'classId',
  slotIndex: 'slotIndex',
  imageUrl: 'imageUrl',
  feedbackText: 'feedbackText',
  tasksText: 'tasksText',
  aiFeedbackText: 'aiFeedbackText',
  isHidden: 'isHidden',
  isExplicitFlag: 'isExplicitFlag',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UploadScalarFieldEnum = (typeof UploadScalarFieldEnum)[keyof typeof UploadScalarFieldEnum]


export const GraduationScalarFieldEnum = {
  id: 'id',
  subscriptionId: 'subscriptionId',
  monthKey: 'monthKey',
  eighthUploadId: 'eighthUploadId',
  approvedBool: 'approvedBool',
  decidedByTeacherId: 'decidedByTeacherId',
  decidedAt: 'decidedAt',
  createdAt: 'createdAt'
} as const

export type GraduationScalarFieldEnum = (typeof GraduationScalarFieldEnum)[keyof typeof GraduationScalarFieldEnum]


export const StickerCatalogScalarFieldEnum = {
  id: 'id',
  name: 'name',
  imageUrl: 'imageUrl',
  priceCents: 'priceCents',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StickerCatalogScalarFieldEnum = (typeof StickerCatalogScalarFieldEnum)[keyof typeof StickerCatalogScalarFieldEnum]


export const GiftCatalogScalarFieldEnum = {
  id: 'id',
  name: 'name',
  imageUrl: 'imageUrl',
  priceCents: 'priceCents',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GiftCatalogScalarFieldEnum = (typeof GiftCatalogScalarFieldEnum)[keyof typeof GiftCatalogScalarFieldEnum]


export const EntitlementScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  monthKey: 'monthKey',
  freeStickersRemaining: 'freeStickersRemaining',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EntitlementScalarFieldEnum = (typeof EntitlementScalarFieldEnum)[keyof typeof EntitlementScalarFieldEnum]


export const BundleScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  totalItems: 'totalItems',
  remainingItems: 'remainingItems',
  perItemValueCents: 'perItemValueCents',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BundleScalarFieldEnum = (typeof BundleScalarFieldEnum)[keyof typeof BundleScalarFieldEnum]


export const ChatBundlePricingScalarFieldEnum = {
  id: 'id',
  type: 'type',
  bundlePriceCents: 'bundlePriceCents',
  totalItems: 'totalItems',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ChatBundlePricingScalarFieldEnum = (typeof ChatBundlePricingScalarFieldEnum)[keyof typeof ChatBundlePricingScalarFieldEnum]


export const StreamScalarFieldEnum = {
  id: 'id',
  type: 'type',
  ownerId: 'ownerId',
  classId: 'classId',
  status: 'status',
  roomName: 'roomName',
  startedAt: 'startedAt',
  endedAt: 'endedAt',
  recordingUrl: 'recordingUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StreamScalarFieldEnum = (typeof StreamScalarFieldEnum)[keyof typeof StreamScalarFieldEnum]


export const StreamRecordingScalarFieldEnum = {
  id: 'id',
  streamId: 'streamId',
  status: 'status',
  storageProvider: 'storageProvider',
  objectKey: 'objectKey',
  downloadUrl: 'downloadUrl',
  mimeType: 'mimeType',
  sizeBytes: 'sizeBytes',
  durationSeconds: 'durationSeconds',
  recordedStartedAt: 'recordedStartedAt',
  recordedEndedAt: 'recordedEndedAt',
  availableAt: 'availableAt',
  expiresAt: 'expiresAt',
  expiredAt: 'expiredAt',
  failureReason: 'failureReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StreamRecordingScalarFieldEnum = (typeof StreamRecordingScalarFieldEnum)[keyof typeof StreamRecordingScalarFieldEnum]


export const RecordingDownloadAuditScalarFieldEnum = {
  id: 'id',
  recordingId: 'recordingId',
  adminUserId: 'adminUserId',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt'
} as const

export type RecordingDownloadAuditScalarFieldEnum = (typeof RecordingDownloadAuditScalarFieldEnum)[keyof typeof RecordingDownloadAuditScalarFieldEnum]


export const ChatMessageScalarFieldEnum = {
  id: 'id',
  streamId: 'streamId',
  userId: 'userId',
  message: 'message',
  createdAt: 'createdAt'
} as const

export type ChatMessageScalarFieldEnum = (typeof ChatMessageScalarFieldEnum)[keyof typeof ChatMessageScalarFieldEnum]


export const TransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  amountCents: 'amountCents',
  provider: 'provider',
  providerTxId: 'providerTxId',
  status: 'status',
  metadataJson: 'metadataJson',
  createdAt: 'createdAt'
} as const

export type TransactionScalarFieldEnum = (typeof TransactionScalarFieldEnum)[keyof typeof TransactionScalarFieldEnum]


export const LikeScalarFieldEnum = {
  id: 'id',
  likerUserId: 'likerUserId',
  targetType: 'targetType',
  targetId: 'targetId',
  createdAt: 'createdAt'
} as const

export type LikeScalarFieldEnum = (typeof LikeScalarFieldEnum)[keyof typeof LikeScalarFieldEnum]


export const FeaturedSlotScalarFieldEnum = {
  id: 'id',
  monthKey: 'monthKey',
  slotIndex: 'slotIndex',
  graduationUploadId: 'graduationUploadId',
  studentUserId: 'studentUserId',
  adminId: 'adminId',
  createdAt: 'createdAt'
} as const

export type FeaturedSlotScalarFieldEnum = (typeof FeaturedSlotScalarFieldEnum)[keyof typeof FeaturedSlotScalarFieldEnum]


export const AdminTaskScalarFieldEnum = {
  id: 'id',
  type: 'type',
  payloadJson: 'payloadJson',
  status: 'status',
  createdById: 'createdById',
  assigneeId: 'assigneeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  closedAt: 'closedAt'
} as const

export type AdminTaskScalarFieldEnum = (typeof AdminTaskScalarFieldEnum)[keyof typeof AdminTaskScalarFieldEnum]


export const AccountGrantScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  lessonLimit: 'lessonLimit',
  lessonsUsed: 'lessonsUsed',
  active: 'active',
  reason: 'reason',
  createdByAdminId: 'createdByAdminId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AccountGrantScalarFieldEnum = (typeof AccountGrantScalarFieldEnum)[keyof typeof AccountGrantScalarFieldEnum]


export const CustomGroupOrderScalarFieldEnum = {
  id: 'id',
  sourceSupportTaskId: 'sourceSupportTaskId',
  status: 'status',
  numberOfSeats: 'numberOfSeats',
  claimedSeats: 'claimedSeats',
  country: 'country',
  preferredDaysTimes: 'preferredDaysTimes',
  ageRange: 'ageRange',
  note: 'note',
  contactEmail: 'contactEmail',
  seatPriceCents: 'seatPriceCents',
  totalAmountCents: 'totalAmountCents',
  checkoutUrl: 'checkoutUrl',
  checkoutReference: 'checkoutReference',
  paidAt: 'paidAt',
  activatedAt: 'activatedAt',
  closedAt: 'closedAt',
  canceledAt: 'canceledAt',
  groupAdminUserId: 'groupAdminUserId',
  createdByAdminId: 'createdByAdminId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CustomGroupOrderScalarFieldEnum = (typeof CustomGroupOrderScalarFieldEnum)[keyof typeof CustomGroupOrderScalarFieldEnum]


export const CustomGroupSeatScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  seatIndex: 'seatIndex',
  status: 'status',
  claimToken: 'claimToken',
  invitedEmail: 'invitedEmail',
  claimedByUserId: 'claimedByUserId',
  claimedAt: 'claimedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CustomGroupSeatScalarFieldEnum = (typeof CustomGroupSeatScalarFieldEnum)[keyof typeof CustomGroupSeatScalarFieldEnum]


export const PaymentWebhookEventScalarFieldEnum = {
  id: 'id',
  provider: 'provider',
  deliveryId: 'deliveryId',
  providerTxId: 'providerTxId',
  payloadHash: 'payloadHash',
  signatureHash: 'signatureHash',
  receivedStatus: 'receivedStatus',
  processed: 'processed',
  createdAt: 'createdAt',
  processedAt: 'processedAt'
} as const

export type PaymentWebhookEventScalarFieldEnum = (typeof PaymentWebhookEventScalarFieldEnum)[keyof typeof PaymentWebhookEventScalarFieldEnum]


export const DeviceSessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tokenHash: 'tokenHash',
  userAgent: 'userAgent',
  ipAddress: 'ipAddress',
  countryCode: 'countryCode',
  lastSeenAt: 'lastSeenAt',
  createdAt: 'createdAt',
  revokedAt: 'revokedAt'
} as const

export type DeviceSessionScalarFieldEnum = (typeof DeviceSessionScalarFieldEnum)[keyof typeof DeviceSessionScalarFieldEnum]


export const TrialAttendanceScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  streamId: 'streamId',
  createdAt: 'createdAt'
} as const

export type TrialAttendanceScalarFieldEnum = (typeof TrialAttendanceScalarFieldEnum)[keyof typeof TrialAttendanceScalarFieldEnum]


export const PageContentBlockScalarFieldEnum = {
  id: 'id',
  pageKey: 'pageKey',
  sectionKey: 'sectionKey',
  title: 'title',
  bodyText: 'bodyText',
  ctaLabel: 'ctaLabel',
  ctaHref: 'ctaHref',
  ctaSecondaryLabel: 'ctaSecondaryLabel',
  ctaSecondaryHref: 'ctaSecondaryHref',
  imageUrl: 'imageUrl',
  sortOrder: 'sortOrder',
  isPublished: 'isPublished',
  updatedByAdminId: 'updatedByAdminId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PageContentBlockScalarFieldEnum = (typeof PageContentBlockScalarFieldEnum)[keyof typeof PageContentBlockScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

