
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StreamRecording` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StreamRecording
 * 
 */
export type StreamRecordingModel = runtime.Types.Result.DefaultSelection<Prisma.$StreamRecordingPayload>

export type AggregateStreamRecording = {
  _count: StreamRecordingCountAggregateOutputType | null
  _avg: StreamRecordingAvgAggregateOutputType | null
  _sum: StreamRecordingSumAggregateOutputType | null
  _min: StreamRecordingMinAggregateOutputType | null
  _max: StreamRecordingMaxAggregateOutputType | null
}

export type StreamRecordingAvgAggregateOutputType = {
  sizeBytes: number | null
  durationSeconds: number | null
}

export type StreamRecordingSumAggregateOutputType = {
  sizeBytes: bigint | null
  durationSeconds: number | null
}

export type StreamRecordingMinAggregateOutputType = {
  id: string | null
  streamId: string | null
  status: $Enums.StreamRecordingStatus | null
  storageProvider: string | null
  objectKey: string | null
  downloadUrl: string | null
  mimeType: string | null
  sizeBytes: bigint | null
  durationSeconds: number | null
  recordedStartedAt: Date | null
  recordedEndedAt: Date | null
  availableAt: Date | null
  expiresAt: Date | null
  expiredAt: Date | null
  failureReason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StreamRecordingMaxAggregateOutputType = {
  id: string | null
  streamId: string | null
  status: $Enums.StreamRecordingStatus | null
  storageProvider: string | null
  objectKey: string | null
  downloadUrl: string | null
  mimeType: string | null
  sizeBytes: bigint | null
  durationSeconds: number | null
  recordedStartedAt: Date | null
  recordedEndedAt: Date | null
  availableAt: Date | null
  expiresAt: Date | null
  expiredAt: Date | null
  failureReason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StreamRecordingCountAggregateOutputType = {
  id: number
  streamId: number
  status: number
  storageProvider: number
  objectKey: number
  downloadUrl: number
  mimeType: number
  sizeBytes: number
  durationSeconds: number
  recordedStartedAt: number
  recordedEndedAt: number
  availableAt: number
  expiresAt: number
  expiredAt: number
  failureReason: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type StreamRecordingAvgAggregateInputType = {
  sizeBytes?: true
  durationSeconds?: true
}

export type StreamRecordingSumAggregateInputType = {
  sizeBytes?: true
  durationSeconds?: true
}

export type StreamRecordingMinAggregateInputType = {
  id?: true
  streamId?: true
  status?: true
  storageProvider?: true
  objectKey?: true
  downloadUrl?: true
  mimeType?: true
  sizeBytes?: true
  durationSeconds?: true
  recordedStartedAt?: true
  recordedEndedAt?: true
  availableAt?: true
  expiresAt?: true
  expiredAt?: true
  failureReason?: true
  createdAt?: true
  updatedAt?: true
}

export type StreamRecordingMaxAggregateInputType = {
  id?: true
  streamId?: true
  status?: true
  storageProvider?: true
  objectKey?: true
  downloadUrl?: true
  mimeType?: true
  sizeBytes?: true
  durationSeconds?: true
  recordedStartedAt?: true
  recordedEndedAt?: true
  availableAt?: true
  expiresAt?: true
  expiredAt?: true
  failureReason?: true
  createdAt?: true
  updatedAt?: true
}

export type StreamRecordingCountAggregateInputType = {
  id?: true
  streamId?: true
  status?: true
  storageProvider?: true
  objectKey?: true
  downloadUrl?: true
  mimeType?: true
  sizeBytes?: true
  durationSeconds?: true
  recordedStartedAt?: true
  recordedEndedAt?: true
  availableAt?: true
  expiresAt?: true
  expiredAt?: true
  failureReason?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type StreamRecordingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StreamRecording to aggregate.
   */
  where?: Prisma.StreamRecordingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StreamRecordings to fetch.
   */
  orderBy?: Prisma.StreamRecordingOrderByWithRelationInput | Prisma.StreamRecordingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StreamRecordingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StreamRecordings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StreamRecordings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StreamRecordings
  **/
  _count?: true | StreamRecordingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StreamRecordingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StreamRecordingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StreamRecordingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StreamRecordingMaxAggregateInputType
}

export type GetStreamRecordingAggregateType<T extends StreamRecordingAggregateArgs> = {
      [P in keyof T & keyof AggregateStreamRecording]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStreamRecording[P]>
    : Prisma.GetScalarType<T[P], AggregateStreamRecording[P]>
}




export type StreamRecordingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StreamRecordingWhereInput
  orderBy?: Prisma.StreamRecordingOrderByWithAggregationInput | Prisma.StreamRecordingOrderByWithAggregationInput[]
  by: Prisma.StreamRecordingScalarFieldEnum[] | Prisma.StreamRecordingScalarFieldEnum
  having?: Prisma.StreamRecordingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StreamRecordingCountAggregateInputType | true
  _avg?: StreamRecordingAvgAggregateInputType
  _sum?: StreamRecordingSumAggregateInputType
  _min?: StreamRecordingMinAggregateInputType
  _max?: StreamRecordingMaxAggregateInputType
}

export type StreamRecordingGroupByOutputType = {
  id: string
  streamId: string
  status: $Enums.StreamRecordingStatus
  storageProvider: string
  objectKey: string | null
  downloadUrl: string | null
  mimeType: string | null
  sizeBytes: bigint | null
  durationSeconds: number | null
  recordedStartedAt: Date | null
  recordedEndedAt: Date | null
  availableAt: Date | null
  expiresAt: Date
  expiredAt: Date | null
  failureReason: string | null
  createdAt: Date
  updatedAt: Date
  _count: StreamRecordingCountAggregateOutputType | null
  _avg: StreamRecordingAvgAggregateOutputType | null
  _sum: StreamRecordingSumAggregateOutputType | null
  _min: StreamRecordingMinAggregateOutputType | null
  _max: StreamRecordingMaxAggregateOutputType | null
}

type GetStreamRecordingGroupByPayload<T extends StreamRecordingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StreamRecordingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StreamRecordingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StreamRecordingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StreamRecordingGroupByOutputType[P]>
      }
    >
  >



export type StreamRecordingWhereInput = {
  AND?: Prisma.StreamRecordingWhereInput | Prisma.StreamRecordingWhereInput[]
  OR?: Prisma.StreamRecordingWhereInput[]
  NOT?: Prisma.StreamRecordingWhereInput | Prisma.StreamRecordingWhereInput[]
  id?: Prisma.StringFilter<"StreamRecording"> | string
  streamId?: Prisma.StringFilter<"StreamRecording"> | string
  status?: Prisma.EnumStreamRecordingStatusFilter<"StreamRecording"> | $Enums.StreamRecordingStatus
  storageProvider?: Prisma.StringFilter<"StreamRecording"> | string
  objectKey?: Prisma.StringNullableFilter<"StreamRecording"> | string | null
  downloadUrl?: Prisma.StringNullableFilter<"StreamRecording"> | string | null
  mimeType?: Prisma.StringNullableFilter<"StreamRecording"> | string | null
  sizeBytes?: Prisma.BigIntNullableFilter<"StreamRecording"> | bigint | number | null
  durationSeconds?: Prisma.IntNullableFilter<"StreamRecording"> | number | null
  recordedStartedAt?: Prisma.DateTimeNullableFilter<"StreamRecording"> | Date | string | null
  recordedEndedAt?: Prisma.DateTimeNullableFilter<"StreamRecording"> | Date | string | null
  availableAt?: Prisma.DateTimeNullableFilter<"StreamRecording"> | Date | string | null
  expiresAt?: Prisma.DateTimeFilter<"StreamRecording"> | Date | string
  expiredAt?: Prisma.DateTimeNullableFilter<"StreamRecording"> | Date | string | null
  failureReason?: Prisma.StringNullableFilter<"StreamRecording"> | string | null
  createdAt?: Prisma.DateTimeFilter<"StreamRecording"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StreamRecording"> | Date | string
  stream?: Prisma.XOR<Prisma.StreamScalarRelationFilter, Prisma.StreamWhereInput>
  downloadAudits?: Prisma.RecordingDownloadAuditListRelationFilter
}

export type StreamRecordingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  storageProvider?: Prisma.SortOrder
  objectKey?: Prisma.SortOrderInput | Prisma.SortOrder
  downloadUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  mimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  sizeBytes?: Prisma.SortOrderInput | Prisma.SortOrder
  durationSeconds?: Prisma.SortOrderInput | Prisma.SortOrder
  recordedStartedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  recordedEndedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  availableAt?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrderInput | Prisma.SortOrder
  failureReason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  stream?: Prisma.StreamOrderByWithRelationInput
  downloadAudits?: Prisma.RecordingDownloadAuditOrderByRelationAggregateInput
}

export type StreamRecordingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  streamId?: string
  AND?: Prisma.StreamRecordingWhereInput | Prisma.StreamRecordingWhereInput[]
  OR?: Prisma.StreamRecordingWhereInput[]
  NOT?: Prisma.StreamRecordingWhereInput | Prisma.StreamRecordingWhereInput[]
  status?: Prisma.EnumStreamRecordingStatusFilter<"StreamRecording"> | $Enums.StreamRecordingStatus
  storageProvider?: Prisma.StringFilter<"StreamRecording"> | string
  objectKey?: Prisma.StringNullableFilter<"StreamRecording"> | string | null
  downloadUrl?: Prisma.StringNullableFilter<"StreamRecording"> | string | null
  mimeType?: Prisma.StringNullableFilter<"StreamRecording"> | string | null
  sizeBytes?: Prisma.BigIntNullableFilter<"StreamRecording"> | bigint | number | null
  durationSeconds?: Prisma.IntNullableFilter<"StreamRecording"> | number | null
  recordedStartedAt?: Prisma.DateTimeNullableFilter<"StreamRecording"> | Date | string | null
  recordedEndedAt?: Prisma.DateTimeNullableFilter<"StreamRecording"> | Date | string | null
  availableAt?: Prisma.DateTimeNullableFilter<"StreamRecording"> | Date | string | null
  expiresAt?: Prisma.DateTimeFilter<"StreamRecording"> | Date | string
  expiredAt?: Prisma.DateTimeNullableFilter<"StreamRecording"> | Date | string | null
  failureReason?: Prisma.StringNullableFilter<"StreamRecording"> | string | null
  createdAt?: Prisma.DateTimeFilter<"StreamRecording"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StreamRecording"> | Date | string
  stream?: Prisma.XOR<Prisma.StreamScalarRelationFilter, Prisma.StreamWhereInput>
  downloadAudits?: Prisma.RecordingDownloadAuditListRelationFilter
}, "id" | "streamId">

export type StreamRecordingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  storageProvider?: Prisma.SortOrder
  objectKey?: Prisma.SortOrderInput | Prisma.SortOrder
  downloadUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  mimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  sizeBytes?: Prisma.SortOrderInput | Prisma.SortOrder
  durationSeconds?: Prisma.SortOrderInput | Prisma.SortOrder
  recordedStartedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  recordedEndedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  availableAt?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrderInput | Prisma.SortOrder
  failureReason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.StreamRecordingCountOrderByAggregateInput
  _avg?: Prisma.StreamRecordingAvgOrderByAggregateInput
  _max?: Prisma.StreamRecordingMaxOrderByAggregateInput
  _min?: Prisma.StreamRecordingMinOrderByAggregateInput
  _sum?: Prisma.StreamRecordingSumOrderByAggregateInput
}

export type StreamRecordingScalarWhereWithAggregatesInput = {
  AND?: Prisma.StreamRecordingScalarWhereWithAggregatesInput | Prisma.StreamRecordingScalarWhereWithAggregatesInput[]
  OR?: Prisma.StreamRecordingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StreamRecordingScalarWhereWithAggregatesInput | Prisma.StreamRecordingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StreamRecording"> | string
  streamId?: Prisma.StringWithAggregatesFilter<"StreamRecording"> | string
  status?: Prisma.EnumStreamRecordingStatusWithAggregatesFilter<"StreamRecording"> | $Enums.StreamRecordingStatus
  storageProvider?: Prisma.StringWithAggregatesFilter<"StreamRecording"> | string
  objectKey?: Prisma.StringNullableWithAggregatesFilter<"StreamRecording"> | string | null
  downloadUrl?: Prisma.StringNullableWithAggregatesFilter<"StreamRecording"> | string | null
  mimeType?: Prisma.StringNullableWithAggregatesFilter<"StreamRecording"> | string | null
  sizeBytes?: Prisma.BigIntNullableWithAggregatesFilter<"StreamRecording"> | bigint | number | null
  durationSeconds?: Prisma.IntNullableWithAggregatesFilter<"StreamRecording"> | number | null
  recordedStartedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"StreamRecording"> | Date | string | null
  recordedEndedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"StreamRecording"> | Date | string | null
  availableAt?: Prisma.DateTimeNullableWithAggregatesFilter<"StreamRecording"> | Date | string | null
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"StreamRecording"> | Date | string
  expiredAt?: Prisma.DateTimeNullableWithAggregatesFilter<"StreamRecording"> | Date | string | null
  failureReason?: Prisma.StringNullableWithAggregatesFilter<"StreamRecording"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"StreamRecording"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"StreamRecording"> | Date | string
}

export type StreamRecordingCreateInput = {
  id?: string
  status?: $Enums.StreamRecordingStatus
  storageProvider?: string
  objectKey?: string | null
  downloadUrl?: string | null
  mimeType?: string | null
  sizeBytes?: bigint | number | null
  durationSeconds?: number | null
  recordedStartedAt?: Date | string | null
  recordedEndedAt?: Date | string | null
  availableAt?: Date | string | null
  expiresAt: Date | string
  expiredAt?: Date | string | null
  failureReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  stream: Prisma.StreamCreateNestedOneWithoutRecordingInput
  downloadAudits?: Prisma.RecordingDownloadAuditCreateNestedManyWithoutRecordingInput
}

export type StreamRecordingUncheckedCreateInput = {
  id?: string
  streamId: string
  status?: $Enums.StreamRecordingStatus
  storageProvider?: string
  objectKey?: string | null
  downloadUrl?: string | null
  mimeType?: string | null
  sizeBytes?: bigint | number | null
  durationSeconds?: number | null
  recordedStartedAt?: Date | string | null
  recordedEndedAt?: Date | string | null
  availableAt?: Date | string | null
  expiresAt: Date | string
  expiredAt?: Date | string | null
  failureReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  downloadAudits?: Prisma.RecordingDownloadAuditUncheckedCreateNestedManyWithoutRecordingInput
}

export type StreamRecordingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStreamRecordingStatusFieldUpdateOperationsInput | $Enums.StreamRecordingStatus
  storageProvider?: Prisma.StringFieldUpdateOperationsInput | string
  objectKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  downloadUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  recordedStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  recordedEndedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  availableAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  failureReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stream?: Prisma.StreamUpdateOneRequiredWithoutRecordingNestedInput
  downloadAudits?: Prisma.RecordingDownloadAuditUpdateManyWithoutRecordingNestedInput
}

export type StreamRecordingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStreamRecordingStatusFieldUpdateOperationsInput | $Enums.StreamRecordingStatus
  storageProvider?: Prisma.StringFieldUpdateOperationsInput | string
  objectKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  downloadUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  recordedStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  recordedEndedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  availableAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  failureReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  downloadAudits?: Prisma.RecordingDownloadAuditUncheckedUpdateManyWithoutRecordingNestedInput
}

export type StreamRecordingCreateManyInput = {
  id?: string
  streamId: string
  status?: $Enums.StreamRecordingStatus
  storageProvider?: string
  objectKey?: string | null
  downloadUrl?: string | null
  mimeType?: string | null
  sizeBytes?: bigint | number | null
  durationSeconds?: number | null
  recordedStartedAt?: Date | string | null
  recordedEndedAt?: Date | string | null
  availableAt?: Date | string | null
  expiresAt: Date | string
  expiredAt?: Date | string | null
  failureReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StreamRecordingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStreamRecordingStatusFieldUpdateOperationsInput | $Enums.StreamRecordingStatus
  storageProvider?: Prisma.StringFieldUpdateOperationsInput | string
  objectKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  downloadUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  recordedStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  recordedEndedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  availableAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  failureReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StreamRecordingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStreamRecordingStatusFieldUpdateOperationsInput | $Enums.StreamRecordingStatus
  storageProvider?: Prisma.StringFieldUpdateOperationsInput | string
  objectKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  downloadUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  recordedStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  recordedEndedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  availableAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  failureReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StreamRecordingNullableScalarRelationFilter = {
  is?: Prisma.StreamRecordingWhereInput | null
  isNot?: Prisma.StreamRecordingWhereInput | null
}

export type StreamRecordingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  storageProvider?: Prisma.SortOrder
  objectKey?: Prisma.SortOrder
  downloadUrl?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  recordedStartedAt?: Prisma.SortOrder
  recordedEndedAt?: Prisma.SortOrder
  availableAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  failureReason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StreamRecordingAvgOrderByAggregateInput = {
  sizeBytes?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
}

export type StreamRecordingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  storageProvider?: Prisma.SortOrder
  objectKey?: Prisma.SortOrder
  downloadUrl?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  recordedStartedAt?: Prisma.SortOrder
  recordedEndedAt?: Prisma.SortOrder
  availableAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  failureReason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StreamRecordingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  storageProvider?: Prisma.SortOrder
  objectKey?: Prisma.SortOrder
  downloadUrl?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  recordedStartedAt?: Prisma.SortOrder
  recordedEndedAt?: Prisma.SortOrder
  availableAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  failureReason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StreamRecordingSumOrderByAggregateInput = {
  sizeBytes?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
}

export type StreamRecordingScalarRelationFilter = {
  is?: Prisma.StreamRecordingWhereInput
  isNot?: Prisma.StreamRecordingWhereInput
}

export type StreamRecordingCreateNestedOneWithoutStreamInput = {
  create?: Prisma.XOR<Prisma.StreamRecordingCreateWithoutStreamInput, Prisma.StreamRecordingUncheckedCreateWithoutStreamInput>
  connectOrCreate?: Prisma.StreamRecordingCreateOrConnectWithoutStreamInput
  connect?: Prisma.StreamRecordingWhereUniqueInput
}

export type StreamRecordingUncheckedCreateNestedOneWithoutStreamInput = {
  create?: Prisma.XOR<Prisma.StreamRecordingCreateWithoutStreamInput, Prisma.StreamRecordingUncheckedCreateWithoutStreamInput>
  connectOrCreate?: Prisma.StreamRecordingCreateOrConnectWithoutStreamInput
  connect?: Prisma.StreamRecordingWhereUniqueInput
}

export type StreamRecordingUpdateOneWithoutStreamNestedInput = {
  create?: Prisma.XOR<Prisma.StreamRecordingCreateWithoutStreamInput, Prisma.StreamRecordingUncheckedCreateWithoutStreamInput>
  connectOrCreate?: Prisma.StreamRecordingCreateOrConnectWithoutStreamInput
  upsert?: Prisma.StreamRecordingUpsertWithoutStreamInput
  disconnect?: Prisma.StreamRecordingWhereInput | boolean
  delete?: Prisma.StreamRecordingWhereInput | boolean
  connect?: Prisma.StreamRecordingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StreamRecordingUpdateToOneWithWhereWithoutStreamInput, Prisma.StreamRecordingUpdateWithoutStreamInput>, Prisma.StreamRecordingUncheckedUpdateWithoutStreamInput>
}

export type StreamRecordingUncheckedUpdateOneWithoutStreamNestedInput = {
  create?: Prisma.XOR<Prisma.StreamRecordingCreateWithoutStreamInput, Prisma.StreamRecordingUncheckedCreateWithoutStreamInput>
  connectOrCreate?: Prisma.StreamRecordingCreateOrConnectWithoutStreamInput
  upsert?: Prisma.StreamRecordingUpsertWithoutStreamInput
  disconnect?: Prisma.StreamRecordingWhereInput | boolean
  delete?: Prisma.StreamRecordingWhereInput | boolean
  connect?: Prisma.StreamRecordingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StreamRecordingUpdateToOneWithWhereWithoutStreamInput, Prisma.StreamRecordingUpdateWithoutStreamInput>, Prisma.StreamRecordingUncheckedUpdateWithoutStreamInput>
}

export type EnumStreamRecordingStatusFieldUpdateOperationsInput = {
  set?: $Enums.StreamRecordingStatus
}

export type NullableBigIntFieldUpdateOperationsInput = {
  set?: bigint | number | null
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}

export type StreamRecordingCreateNestedOneWithoutDownloadAuditsInput = {
  create?: Prisma.XOR<Prisma.StreamRecordingCreateWithoutDownloadAuditsInput, Prisma.StreamRecordingUncheckedCreateWithoutDownloadAuditsInput>
  connectOrCreate?: Prisma.StreamRecordingCreateOrConnectWithoutDownloadAuditsInput
  connect?: Prisma.StreamRecordingWhereUniqueInput
}

export type StreamRecordingUpdateOneRequiredWithoutDownloadAuditsNestedInput = {
  create?: Prisma.XOR<Prisma.StreamRecordingCreateWithoutDownloadAuditsInput, Prisma.StreamRecordingUncheckedCreateWithoutDownloadAuditsInput>
  connectOrCreate?: Prisma.StreamRecordingCreateOrConnectWithoutDownloadAuditsInput
  upsert?: Prisma.StreamRecordingUpsertWithoutDownloadAuditsInput
  connect?: Prisma.StreamRecordingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StreamRecordingUpdateToOneWithWhereWithoutDownloadAuditsInput, Prisma.StreamRecordingUpdateWithoutDownloadAuditsInput>, Prisma.StreamRecordingUncheckedUpdateWithoutDownloadAuditsInput>
}

export type StreamRecordingCreateWithoutStreamInput = {
  id?: string
  status?: $Enums.StreamRecordingStatus
  storageProvider?: string
  objectKey?: string | null
  downloadUrl?: string | null
  mimeType?: string | null
  sizeBytes?: bigint | number | null
  durationSeconds?: number | null
  recordedStartedAt?: Date | string | null
  recordedEndedAt?: Date | string | null
  availableAt?: Date | string | null
  expiresAt: Date | string
  expiredAt?: Date | string | null
  failureReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  downloadAudits?: Prisma.RecordingDownloadAuditCreateNestedManyWithoutRecordingInput
}

export type StreamRecordingUncheckedCreateWithoutStreamInput = {
  id?: string
  status?: $Enums.StreamRecordingStatus
  storageProvider?: string
  objectKey?: string | null
  downloadUrl?: string | null
  mimeType?: string | null
  sizeBytes?: bigint | number | null
  durationSeconds?: number | null
  recordedStartedAt?: Date | string | null
  recordedEndedAt?: Date | string | null
  availableAt?: Date | string | null
  expiresAt: Date | string
  expiredAt?: Date | string | null
  failureReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  downloadAudits?: Prisma.RecordingDownloadAuditUncheckedCreateNestedManyWithoutRecordingInput
}

export type StreamRecordingCreateOrConnectWithoutStreamInput = {
  where: Prisma.StreamRecordingWhereUniqueInput
  create: Prisma.XOR<Prisma.StreamRecordingCreateWithoutStreamInput, Prisma.StreamRecordingUncheckedCreateWithoutStreamInput>
}

export type StreamRecordingUpsertWithoutStreamInput = {
  update: Prisma.XOR<Prisma.StreamRecordingUpdateWithoutStreamInput, Prisma.StreamRecordingUncheckedUpdateWithoutStreamInput>
  create: Prisma.XOR<Prisma.StreamRecordingCreateWithoutStreamInput, Prisma.StreamRecordingUncheckedCreateWithoutStreamInput>
  where?: Prisma.StreamRecordingWhereInput
}

export type StreamRecordingUpdateToOneWithWhereWithoutStreamInput = {
  where?: Prisma.StreamRecordingWhereInput
  data: Prisma.XOR<Prisma.StreamRecordingUpdateWithoutStreamInput, Prisma.StreamRecordingUncheckedUpdateWithoutStreamInput>
}

export type StreamRecordingUpdateWithoutStreamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStreamRecordingStatusFieldUpdateOperationsInput | $Enums.StreamRecordingStatus
  storageProvider?: Prisma.StringFieldUpdateOperationsInput | string
  objectKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  downloadUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  recordedStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  recordedEndedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  availableAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  failureReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  downloadAudits?: Prisma.RecordingDownloadAuditUpdateManyWithoutRecordingNestedInput
}

export type StreamRecordingUncheckedUpdateWithoutStreamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStreamRecordingStatusFieldUpdateOperationsInput | $Enums.StreamRecordingStatus
  storageProvider?: Prisma.StringFieldUpdateOperationsInput | string
  objectKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  downloadUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  recordedStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  recordedEndedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  availableAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  failureReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  downloadAudits?: Prisma.RecordingDownloadAuditUncheckedUpdateManyWithoutRecordingNestedInput
}

export type StreamRecordingCreateWithoutDownloadAuditsInput = {
  id?: string
  status?: $Enums.StreamRecordingStatus
  storageProvider?: string
  objectKey?: string | null
  downloadUrl?: string | null
  mimeType?: string | null
  sizeBytes?: bigint | number | null
  durationSeconds?: number | null
  recordedStartedAt?: Date | string | null
  recordedEndedAt?: Date | string | null
  availableAt?: Date | string | null
  expiresAt: Date | string
  expiredAt?: Date | string | null
  failureReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  stream: Prisma.StreamCreateNestedOneWithoutRecordingInput
}

export type StreamRecordingUncheckedCreateWithoutDownloadAuditsInput = {
  id?: string
  streamId: string
  status?: $Enums.StreamRecordingStatus
  storageProvider?: string
  objectKey?: string | null
  downloadUrl?: string | null
  mimeType?: string | null
  sizeBytes?: bigint | number | null
  durationSeconds?: number | null
  recordedStartedAt?: Date | string | null
  recordedEndedAt?: Date | string | null
  availableAt?: Date | string | null
  expiresAt: Date | string
  expiredAt?: Date | string | null
  failureReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StreamRecordingCreateOrConnectWithoutDownloadAuditsInput = {
  where: Prisma.StreamRecordingWhereUniqueInput
  create: Prisma.XOR<Prisma.StreamRecordingCreateWithoutDownloadAuditsInput, Prisma.StreamRecordingUncheckedCreateWithoutDownloadAuditsInput>
}

export type StreamRecordingUpsertWithoutDownloadAuditsInput = {
  update: Prisma.XOR<Prisma.StreamRecordingUpdateWithoutDownloadAuditsInput, Prisma.StreamRecordingUncheckedUpdateWithoutDownloadAuditsInput>
  create: Prisma.XOR<Prisma.StreamRecordingCreateWithoutDownloadAuditsInput, Prisma.StreamRecordingUncheckedCreateWithoutDownloadAuditsInput>
  where?: Prisma.StreamRecordingWhereInput
}

export type StreamRecordingUpdateToOneWithWhereWithoutDownloadAuditsInput = {
  where?: Prisma.StreamRecordingWhereInput
  data: Prisma.XOR<Prisma.StreamRecordingUpdateWithoutDownloadAuditsInput, Prisma.StreamRecordingUncheckedUpdateWithoutDownloadAuditsInput>
}

export type StreamRecordingUpdateWithoutDownloadAuditsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStreamRecordingStatusFieldUpdateOperationsInput | $Enums.StreamRecordingStatus
  storageProvider?: Prisma.StringFieldUpdateOperationsInput | string
  objectKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  downloadUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  recordedStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  recordedEndedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  availableAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  failureReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stream?: Prisma.StreamUpdateOneRequiredWithoutRecordingNestedInput
}

export type StreamRecordingUncheckedUpdateWithoutDownloadAuditsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStreamRecordingStatusFieldUpdateOperationsInput | $Enums.StreamRecordingStatus
  storageProvider?: Prisma.StringFieldUpdateOperationsInput | string
  objectKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  downloadUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  durationSeconds?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  recordedStartedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  recordedEndedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  availableAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  failureReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type StreamRecordingCountOutputType
 */

export type StreamRecordingCountOutputType = {
  downloadAudits: number
}

export type StreamRecordingCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  downloadAudits?: boolean | StreamRecordingCountOutputTypeCountDownloadAuditsArgs
}

/**
 * StreamRecordingCountOutputType without action
 */
export type StreamRecordingCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecordingCountOutputType
   */
  select?: Prisma.StreamRecordingCountOutputTypeSelect<ExtArgs> | null
}

/**
 * StreamRecordingCountOutputType without action
 */
export type StreamRecordingCountOutputTypeCountDownloadAuditsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecordingDownloadAuditWhereInput
}


export type StreamRecordingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  streamId?: boolean
  status?: boolean
  storageProvider?: boolean
  objectKey?: boolean
  downloadUrl?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  durationSeconds?: boolean
  recordedStartedAt?: boolean
  recordedEndedAt?: boolean
  availableAt?: boolean
  expiresAt?: boolean
  expiredAt?: boolean
  failureReason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  stream?: boolean | Prisma.StreamDefaultArgs<ExtArgs>
  downloadAudits?: boolean | Prisma.StreamRecording$downloadAuditsArgs<ExtArgs>
  _count?: boolean | Prisma.StreamRecordingCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["streamRecording"]>

export type StreamRecordingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  streamId?: boolean
  status?: boolean
  storageProvider?: boolean
  objectKey?: boolean
  downloadUrl?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  durationSeconds?: boolean
  recordedStartedAt?: boolean
  recordedEndedAt?: boolean
  availableAt?: boolean
  expiresAt?: boolean
  expiredAt?: boolean
  failureReason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  stream?: boolean | Prisma.StreamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["streamRecording"]>

export type StreamRecordingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  streamId?: boolean
  status?: boolean
  storageProvider?: boolean
  objectKey?: boolean
  downloadUrl?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  durationSeconds?: boolean
  recordedStartedAt?: boolean
  recordedEndedAt?: boolean
  availableAt?: boolean
  expiresAt?: boolean
  expiredAt?: boolean
  failureReason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  stream?: boolean | Prisma.StreamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["streamRecording"]>

export type StreamRecordingSelectScalar = {
  id?: boolean
  streamId?: boolean
  status?: boolean
  storageProvider?: boolean
  objectKey?: boolean
  downloadUrl?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  durationSeconds?: boolean
  recordedStartedAt?: boolean
  recordedEndedAt?: boolean
  availableAt?: boolean
  expiresAt?: boolean
  expiredAt?: boolean
  failureReason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type StreamRecordingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "streamId" | "status" | "storageProvider" | "objectKey" | "downloadUrl" | "mimeType" | "sizeBytes" | "durationSeconds" | "recordedStartedAt" | "recordedEndedAt" | "availableAt" | "expiresAt" | "expiredAt" | "failureReason" | "createdAt" | "updatedAt", ExtArgs["result"]["streamRecording"]>
export type StreamRecordingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  stream?: boolean | Prisma.StreamDefaultArgs<ExtArgs>
  downloadAudits?: boolean | Prisma.StreamRecording$downloadAuditsArgs<ExtArgs>
  _count?: boolean | Prisma.StreamRecordingCountOutputTypeDefaultArgs<ExtArgs>
}
export type StreamRecordingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  stream?: boolean | Prisma.StreamDefaultArgs<ExtArgs>
}
export type StreamRecordingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  stream?: boolean | Prisma.StreamDefaultArgs<ExtArgs>
}

export type $StreamRecordingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StreamRecording"
  objects: {
    stream: Prisma.$StreamPayload<ExtArgs>
    downloadAudits: Prisma.$RecordingDownloadAuditPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    streamId: string
    status: $Enums.StreamRecordingStatus
    storageProvider: string
    objectKey: string | null
    downloadUrl: string | null
    mimeType: string | null
    sizeBytes: bigint | null
    durationSeconds: number | null
    recordedStartedAt: Date | null
    recordedEndedAt: Date | null
    availableAt: Date | null
    expiresAt: Date
    expiredAt: Date | null
    failureReason: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["streamRecording"]>
  composites: {}
}

export type StreamRecordingGetPayload<S extends boolean | null | undefined | StreamRecordingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StreamRecordingPayload, S>

export type StreamRecordingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StreamRecordingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StreamRecordingCountAggregateInputType | true
  }

export interface StreamRecordingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StreamRecording'], meta: { name: 'StreamRecording' } }
  /**
   * Find zero or one StreamRecording that matches the filter.
   * @param {StreamRecordingFindUniqueArgs} args - Arguments to find a StreamRecording
   * @example
   * // Get one StreamRecording
   * const streamRecording = await prisma.streamRecording.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StreamRecordingFindUniqueArgs>(args: Prisma.SelectSubset<T, StreamRecordingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StreamRecordingClient<runtime.Types.Result.GetResult<Prisma.$StreamRecordingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StreamRecording that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StreamRecordingFindUniqueOrThrowArgs} args - Arguments to find a StreamRecording
   * @example
   * // Get one StreamRecording
   * const streamRecording = await prisma.streamRecording.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StreamRecordingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StreamRecordingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StreamRecordingClient<runtime.Types.Result.GetResult<Prisma.$StreamRecordingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StreamRecording that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StreamRecordingFindFirstArgs} args - Arguments to find a StreamRecording
   * @example
   * // Get one StreamRecording
   * const streamRecording = await prisma.streamRecording.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StreamRecordingFindFirstArgs>(args?: Prisma.SelectSubset<T, StreamRecordingFindFirstArgs<ExtArgs>>): Prisma.Prisma__StreamRecordingClient<runtime.Types.Result.GetResult<Prisma.$StreamRecordingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StreamRecording that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StreamRecordingFindFirstOrThrowArgs} args - Arguments to find a StreamRecording
   * @example
   * // Get one StreamRecording
   * const streamRecording = await prisma.streamRecording.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StreamRecordingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StreamRecordingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StreamRecordingClient<runtime.Types.Result.GetResult<Prisma.$StreamRecordingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StreamRecordings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StreamRecordingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StreamRecordings
   * const streamRecordings = await prisma.streamRecording.findMany()
   * 
   * // Get first 10 StreamRecordings
   * const streamRecordings = await prisma.streamRecording.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const streamRecordingWithIdOnly = await prisma.streamRecording.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StreamRecordingFindManyArgs>(args?: Prisma.SelectSubset<T, StreamRecordingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StreamRecordingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StreamRecording.
   * @param {StreamRecordingCreateArgs} args - Arguments to create a StreamRecording.
   * @example
   * // Create one StreamRecording
   * const StreamRecording = await prisma.streamRecording.create({
   *   data: {
   *     // ... data to create a StreamRecording
   *   }
   * })
   * 
   */
  create<T extends StreamRecordingCreateArgs>(args: Prisma.SelectSubset<T, StreamRecordingCreateArgs<ExtArgs>>): Prisma.Prisma__StreamRecordingClient<runtime.Types.Result.GetResult<Prisma.$StreamRecordingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StreamRecordings.
   * @param {StreamRecordingCreateManyArgs} args - Arguments to create many StreamRecordings.
   * @example
   * // Create many StreamRecordings
   * const streamRecording = await prisma.streamRecording.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StreamRecordingCreateManyArgs>(args?: Prisma.SelectSubset<T, StreamRecordingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StreamRecordings and returns the data saved in the database.
   * @param {StreamRecordingCreateManyAndReturnArgs} args - Arguments to create many StreamRecordings.
   * @example
   * // Create many StreamRecordings
   * const streamRecording = await prisma.streamRecording.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StreamRecordings and only return the `id`
   * const streamRecordingWithIdOnly = await prisma.streamRecording.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StreamRecordingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StreamRecordingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StreamRecordingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StreamRecording.
   * @param {StreamRecordingDeleteArgs} args - Arguments to delete one StreamRecording.
   * @example
   * // Delete one StreamRecording
   * const StreamRecording = await prisma.streamRecording.delete({
   *   where: {
   *     // ... filter to delete one StreamRecording
   *   }
   * })
   * 
   */
  delete<T extends StreamRecordingDeleteArgs>(args: Prisma.SelectSubset<T, StreamRecordingDeleteArgs<ExtArgs>>): Prisma.Prisma__StreamRecordingClient<runtime.Types.Result.GetResult<Prisma.$StreamRecordingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StreamRecording.
   * @param {StreamRecordingUpdateArgs} args - Arguments to update one StreamRecording.
   * @example
   * // Update one StreamRecording
   * const streamRecording = await prisma.streamRecording.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StreamRecordingUpdateArgs>(args: Prisma.SelectSubset<T, StreamRecordingUpdateArgs<ExtArgs>>): Prisma.Prisma__StreamRecordingClient<runtime.Types.Result.GetResult<Prisma.$StreamRecordingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StreamRecordings.
   * @param {StreamRecordingDeleteManyArgs} args - Arguments to filter StreamRecordings to delete.
   * @example
   * // Delete a few StreamRecordings
   * const { count } = await prisma.streamRecording.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StreamRecordingDeleteManyArgs>(args?: Prisma.SelectSubset<T, StreamRecordingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StreamRecordings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StreamRecordingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StreamRecordings
   * const streamRecording = await prisma.streamRecording.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StreamRecordingUpdateManyArgs>(args: Prisma.SelectSubset<T, StreamRecordingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StreamRecordings and returns the data updated in the database.
   * @param {StreamRecordingUpdateManyAndReturnArgs} args - Arguments to update many StreamRecordings.
   * @example
   * // Update many StreamRecordings
   * const streamRecording = await prisma.streamRecording.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StreamRecordings and only return the `id`
   * const streamRecordingWithIdOnly = await prisma.streamRecording.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StreamRecordingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StreamRecordingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StreamRecordingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StreamRecording.
   * @param {StreamRecordingUpsertArgs} args - Arguments to update or create a StreamRecording.
   * @example
   * // Update or create a StreamRecording
   * const streamRecording = await prisma.streamRecording.upsert({
   *   create: {
   *     // ... data to create a StreamRecording
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StreamRecording we want to update
   *   }
   * })
   */
  upsert<T extends StreamRecordingUpsertArgs>(args: Prisma.SelectSubset<T, StreamRecordingUpsertArgs<ExtArgs>>): Prisma.Prisma__StreamRecordingClient<runtime.Types.Result.GetResult<Prisma.$StreamRecordingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StreamRecordings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StreamRecordingCountArgs} args - Arguments to filter StreamRecordings to count.
   * @example
   * // Count the number of StreamRecordings
   * const count = await prisma.streamRecording.count({
   *   where: {
   *     // ... the filter for the StreamRecordings we want to count
   *   }
   * })
  **/
  count<T extends StreamRecordingCountArgs>(
    args?: Prisma.Subset<T, StreamRecordingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StreamRecordingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StreamRecording.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StreamRecordingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StreamRecordingAggregateArgs>(args: Prisma.Subset<T, StreamRecordingAggregateArgs>): Prisma.PrismaPromise<GetStreamRecordingAggregateType<T>>

  /**
   * Group by StreamRecording.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StreamRecordingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StreamRecordingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StreamRecordingGroupByArgs['orderBy'] }
      : { orderBy?: StreamRecordingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StreamRecordingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStreamRecordingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StreamRecording model
 */
readonly fields: StreamRecordingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StreamRecording.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StreamRecordingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  stream<T extends Prisma.StreamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StreamDefaultArgs<ExtArgs>>): Prisma.Prisma__StreamClient<runtime.Types.Result.GetResult<Prisma.$StreamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  downloadAudits<T extends Prisma.StreamRecording$downloadAuditsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StreamRecording$downloadAuditsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordingDownloadAuditPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StreamRecording model
 */
export interface StreamRecordingFieldRefs {
  readonly id: Prisma.FieldRef<"StreamRecording", 'String'>
  readonly streamId: Prisma.FieldRef<"StreamRecording", 'String'>
  readonly status: Prisma.FieldRef<"StreamRecording", 'StreamRecordingStatus'>
  readonly storageProvider: Prisma.FieldRef<"StreamRecording", 'String'>
  readonly objectKey: Prisma.FieldRef<"StreamRecording", 'String'>
  readonly downloadUrl: Prisma.FieldRef<"StreamRecording", 'String'>
  readonly mimeType: Prisma.FieldRef<"StreamRecording", 'String'>
  readonly sizeBytes: Prisma.FieldRef<"StreamRecording", 'BigInt'>
  readonly durationSeconds: Prisma.FieldRef<"StreamRecording", 'Int'>
  readonly recordedStartedAt: Prisma.FieldRef<"StreamRecording", 'DateTime'>
  readonly recordedEndedAt: Prisma.FieldRef<"StreamRecording", 'DateTime'>
  readonly availableAt: Prisma.FieldRef<"StreamRecording", 'DateTime'>
  readonly expiresAt: Prisma.FieldRef<"StreamRecording", 'DateTime'>
  readonly expiredAt: Prisma.FieldRef<"StreamRecording", 'DateTime'>
  readonly failureReason: Prisma.FieldRef<"StreamRecording", 'String'>
  readonly createdAt: Prisma.FieldRef<"StreamRecording", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"StreamRecording", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StreamRecording findUnique
 */
export type StreamRecordingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecording
   */
  select?: Prisma.StreamRecordingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StreamRecording
   */
  omit?: Prisma.StreamRecordingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StreamRecordingInclude<ExtArgs> | null
  /**
   * Filter, which StreamRecording to fetch.
   */
  where: Prisma.StreamRecordingWhereUniqueInput
}

/**
 * StreamRecording findUniqueOrThrow
 */
export type StreamRecordingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecording
   */
  select?: Prisma.StreamRecordingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StreamRecording
   */
  omit?: Prisma.StreamRecordingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StreamRecordingInclude<ExtArgs> | null
  /**
   * Filter, which StreamRecording to fetch.
   */
  where: Prisma.StreamRecordingWhereUniqueInput
}

/**
 * StreamRecording findFirst
 */
export type StreamRecordingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecording
   */
  select?: Prisma.StreamRecordingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StreamRecording
   */
  omit?: Prisma.StreamRecordingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StreamRecordingInclude<ExtArgs> | null
  /**
   * Filter, which StreamRecording to fetch.
   */
  where?: Prisma.StreamRecordingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StreamRecordings to fetch.
   */
  orderBy?: Prisma.StreamRecordingOrderByWithRelationInput | Prisma.StreamRecordingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StreamRecordings.
   */
  cursor?: Prisma.StreamRecordingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StreamRecordings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StreamRecordings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StreamRecordings.
   */
  distinct?: Prisma.StreamRecordingScalarFieldEnum | Prisma.StreamRecordingScalarFieldEnum[]
}

/**
 * StreamRecording findFirstOrThrow
 */
export type StreamRecordingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecording
   */
  select?: Prisma.StreamRecordingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StreamRecording
   */
  omit?: Prisma.StreamRecordingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StreamRecordingInclude<ExtArgs> | null
  /**
   * Filter, which StreamRecording to fetch.
   */
  where?: Prisma.StreamRecordingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StreamRecordings to fetch.
   */
  orderBy?: Prisma.StreamRecordingOrderByWithRelationInput | Prisma.StreamRecordingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StreamRecordings.
   */
  cursor?: Prisma.StreamRecordingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StreamRecordings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StreamRecordings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StreamRecordings.
   */
  distinct?: Prisma.StreamRecordingScalarFieldEnum | Prisma.StreamRecordingScalarFieldEnum[]
}

/**
 * StreamRecording findMany
 */
export type StreamRecordingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecording
   */
  select?: Prisma.StreamRecordingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StreamRecording
   */
  omit?: Prisma.StreamRecordingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StreamRecordingInclude<ExtArgs> | null
  /**
   * Filter, which StreamRecordings to fetch.
   */
  where?: Prisma.StreamRecordingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StreamRecordings to fetch.
   */
  orderBy?: Prisma.StreamRecordingOrderByWithRelationInput | Prisma.StreamRecordingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StreamRecordings.
   */
  cursor?: Prisma.StreamRecordingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StreamRecordings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StreamRecordings.
   */
  skip?: number
  distinct?: Prisma.StreamRecordingScalarFieldEnum | Prisma.StreamRecordingScalarFieldEnum[]
}

/**
 * StreamRecording create
 */
export type StreamRecordingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecording
   */
  select?: Prisma.StreamRecordingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StreamRecording
   */
  omit?: Prisma.StreamRecordingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StreamRecordingInclude<ExtArgs> | null
  /**
   * The data needed to create a StreamRecording.
   */
  data: Prisma.XOR<Prisma.StreamRecordingCreateInput, Prisma.StreamRecordingUncheckedCreateInput>
}

/**
 * StreamRecording createMany
 */
export type StreamRecordingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StreamRecordings.
   */
  data: Prisma.StreamRecordingCreateManyInput | Prisma.StreamRecordingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StreamRecording createManyAndReturn
 */
export type StreamRecordingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecording
   */
  select?: Prisma.StreamRecordingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StreamRecording
   */
  omit?: Prisma.StreamRecordingOmit<ExtArgs> | null
  /**
   * The data used to create many StreamRecordings.
   */
  data: Prisma.StreamRecordingCreateManyInput | Prisma.StreamRecordingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StreamRecordingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StreamRecording update
 */
export type StreamRecordingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecording
   */
  select?: Prisma.StreamRecordingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StreamRecording
   */
  omit?: Prisma.StreamRecordingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StreamRecordingInclude<ExtArgs> | null
  /**
   * The data needed to update a StreamRecording.
   */
  data: Prisma.XOR<Prisma.StreamRecordingUpdateInput, Prisma.StreamRecordingUncheckedUpdateInput>
  /**
   * Choose, which StreamRecording to update.
   */
  where: Prisma.StreamRecordingWhereUniqueInput
}

/**
 * StreamRecording updateMany
 */
export type StreamRecordingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StreamRecordings.
   */
  data: Prisma.XOR<Prisma.StreamRecordingUpdateManyMutationInput, Prisma.StreamRecordingUncheckedUpdateManyInput>
  /**
   * Filter which StreamRecordings to update
   */
  where?: Prisma.StreamRecordingWhereInput
  /**
   * Limit how many StreamRecordings to update.
   */
  limit?: number
}

/**
 * StreamRecording updateManyAndReturn
 */
export type StreamRecordingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecording
   */
  select?: Prisma.StreamRecordingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StreamRecording
   */
  omit?: Prisma.StreamRecordingOmit<ExtArgs> | null
  /**
   * The data used to update StreamRecordings.
   */
  data: Prisma.XOR<Prisma.StreamRecordingUpdateManyMutationInput, Prisma.StreamRecordingUncheckedUpdateManyInput>
  /**
   * Filter which StreamRecordings to update
   */
  where?: Prisma.StreamRecordingWhereInput
  /**
   * Limit how many StreamRecordings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StreamRecordingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StreamRecording upsert
 */
export type StreamRecordingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecording
   */
  select?: Prisma.StreamRecordingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StreamRecording
   */
  omit?: Prisma.StreamRecordingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StreamRecordingInclude<ExtArgs> | null
  /**
   * The filter to search for the StreamRecording to update in case it exists.
   */
  where: Prisma.StreamRecordingWhereUniqueInput
  /**
   * In case the StreamRecording found by the `where` argument doesn't exist, create a new StreamRecording with this data.
   */
  create: Prisma.XOR<Prisma.StreamRecordingCreateInput, Prisma.StreamRecordingUncheckedCreateInput>
  /**
   * In case the StreamRecording was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StreamRecordingUpdateInput, Prisma.StreamRecordingUncheckedUpdateInput>
}

/**
 * StreamRecording delete
 */
export type StreamRecordingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecording
   */
  select?: Prisma.StreamRecordingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StreamRecording
   */
  omit?: Prisma.StreamRecordingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StreamRecordingInclude<ExtArgs> | null
  /**
   * Filter which StreamRecording to delete.
   */
  where: Prisma.StreamRecordingWhereUniqueInput
}

/**
 * StreamRecording deleteMany
 */
export type StreamRecordingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StreamRecordings to delete
   */
  where?: Prisma.StreamRecordingWhereInput
  /**
   * Limit how many StreamRecordings to delete.
   */
  limit?: number
}

/**
 * StreamRecording.downloadAudits
 */
export type StreamRecording$downloadAuditsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordingDownloadAudit
   */
  select?: Prisma.RecordingDownloadAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordingDownloadAudit
   */
  omit?: Prisma.RecordingDownloadAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordingDownloadAuditInclude<ExtArgs> | null
  where?: Prisma.RecordingDownloadAuditWhereInput
  orderBy?: Prisma.RecordingDownloadAuditOrderByWithRelationInput | Prisma.RecordingDownloadAuditOrderByWithRelationInput[]
  cursor?: Prisma.RecordingDownloadAuditWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RecordingDownloadAuditScalarFieldEnum | Prisma.RecordingDownloadAuditScalarFieldEnum[]
}

/**
 * StreamRecording without action
 */
export type StreamRecordingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StreamRecording
   */
  select?: Prisma.StreamRecordingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StreamRecording
   */
  omit?: Prisma.StreamRecordingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StreamRecordingInclude<ExtArgs> | null
}
