
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Upload` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Upload
 * 
 */
export type UploadModel = runtime.Types.Result.DefaultSelection<Prisma.$UploadPayload>

export type AggregateUpload = {
  _count: UploadCountAggregateOutputType | null
  _avg: UploadAvgAggregateOutputType | null
  _sum: UploadSumAggregateOutputType | null
  _min: UploadMinAggregateOutputType | null
  _max: UploadMaxAggregateOutputType | null
}

export type UploadAvgAggregateOutputType = {
  slotIndex: number | null
}

export type UploadSumAggregateOutputType = {
  slotIndex: number | null
}

export type UploadMinAggregateOutputType = {
  id: string | null
  userId: string | null
  subscriptionId: string | null
  classId: string | null
  slotIndex: number | null
  imageUrl: string | null
  feedbackText: string | null
  tasksText: string | null
  aiFeedbackText: string | null
  isHidden: boolean | null
  isExplicitFlag: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UploadMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  subscriptionId: string | null
  classId: string | null
  slotIndex: number | null
  imageUrl: string | null
  feedbackText: string | null
  tasksText: string | null
  aiFeedbackText: string | null
  isHidden: boolean | null
  isExplicitFlag: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UploadCountAggregateOutputType = {
  id: number
  userId: number
  subscriptionId: number
  classId: number
  slotIndex: number
  imageUrl: number
  feedbackText: number
  tasksText: number
  aiFeedbackText: number
  isHidden: number
  isExplicitFlag: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UploadAvgAggregateInputType = {
  slotIndex?: true
}

export type UploadSumAggregateInputType = {
  slotIndex?: true
}

export type UploadMinAggregateInputType = {
  id?: true
  userId?: true
  subscriptionId?: true
  classId?: true
  slotIndex?: true
  imageUrl?: true
  feedbackText?: true
  tasksText?: true
  aiFeedbackText?: true
  isHidden?: true
  isExplicitFlag?: true
  createdAt?: true
  updatedAt?: true
}

export type UploadMaxAggregateInputType = {
  id?: true
  userId?: true
  subscriptionId?: true
  classId?: true
  slotIndex?: true
  imageUrl?: true
  feedbackText?: true
  tasksText?: true
  aiFeedbackText?: true
  isHidden?: true
  isExplicitFlag?: true
  createdAt?: true
  updatedAt?: true
}

export type UploadCountAggregateInputType = {
  id?: true
  userId?: true
  subscriptionId?: true
  classId?: true
  slotIndex?: true
  imageUrl?: true
  feedbackText?: true
  tasksText?: true
  aiFeedbackText?: true
  isHidden?: true
  isExplicitFlag?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UploadAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Upload to aggregate.
   */
  where?: Prisma.UploadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Uploads to fetch.
   */
  orderBy?: Prisma.UploadOrderByWithRelationInput | Prisma.UploadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UploadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Uploads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Uploads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Uploads
  **/
  _count?: true | UploadCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UploadAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UploadSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UploadMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UploadMaxAggregateInputType
}

export type GetUploadAggregateType<T extends UploadAggregateArgs> = {
      [P in keyof T & keyof AggregateUpload]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUpload[P]>
    : Prisma.GetScalarType<T[P], AggregateUpload[P]>
}




export type UploadGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UploadWhereInput
  orderBy?: Prisma.UploadOrderByWithAggregationInput | Prisma.UploadOrderByWithAggregationInput[]
  by: Prisma.UploadScalarFieldEnum[] | Prisma.UploadScalarFieldEnum
  having?: Prisma.UploadScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UploadCountAggregateInputType | true
  _avg?: UploadAvgAggregateInputType
  _sum?: UploadSumAggregateInputType
  _min?: UploadMinAggregateInputType
  _max?: UploadMaxAggregateInputType
}

export type UploadGroupByOutputType = {
  id: string
  userId: string
  subscriptionId: string
  classId: string
  slotIndex: number
  imageUrl: string
  feedbackText: string | null
  tasksText: string | null
  aiFeedbackText: string | null
  isHidden: boolean
  isExplicitFlag: boolean
  createdAt: Date
  updatedAt: Date
  _count: UploadCountAggregateOutputType | null
  _avg: UploadAvgAggregateOutputType | null
  _sum: UploadSumAggregateOutputType | null
  _min: UploadMinAggregateOutputType | null
  _max: UploadMaxAggregateOutputType | null
}

type GetUploadGroupByPayload<T extends UploadGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UploadGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UploadGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UploadGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UploadGroupByOutputType[P]>
      }
    >
  >



export type UploadWhereInput = {
  AND?: Prisma.UploadWhereInput | Prisma.UploadWhereInput[]
  OR?: Prisma.UploadWhereInput[]
  NOT?: Prisma.UploadWhereInput | Prisma.UploadWhereInput[]
  id?: Prisma.StringFilter<"Upload"> | string
  userId?: Prisma.StringFilter<"Upload"> | string
  subscriptionId?: Prisma.StringFilter<"Upload"> | string
  classId?: Prisma.StringFilter<"Upload"> | string
  slotIndex?: Prisma.IntFilter<"Upload"> | number
  imageUrl?: Prisma.StringFilter<"Upload"> | string
  feedbackText?: Prisma.StringNullableFilter<"Upload"> | string | null
  tasksText?: Prisma.StringNullableFilter<"Upload"> | string | null
  aiFeedbackText?: Prisma.StringNullableFilter<"Upload"> | string | null
  isHidden?: Prisma.BoolFilter<"Upload"> | boolean
  isExplicitFlag?: Prisma.BoolFilter<"Upload"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Upload"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Upload"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  subscription?: Prisma.XOR<Prisma.SubscriptionScalarRelationFilter, Prisma.SubscriptionWhereInput>
  class?: Prisma.XOR<Prisma.ClassScalarRelationFilter, Prisma.ClassWhereInput>
  eighthGraduations?: Prisma.GraduationListRelationFilter
}

export type UploadOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  slotIndex?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  feedbackText?: Prisma.SortOrderInput | Prisma.SortOrder
  tasksText?: Prisma.SortOrderInput | Prisma.SortOrder
  aiFeedbackText?: Prisma.SortOrderInput | Prisma.SortOrder
  isHidden?: Prisma.SortOrder
  isExplicitFlag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  subscription?: Prisma.SubscriptionOrderByWithRelationInput
  class?: Prisma.ClassOrderByWithRelationInput
  eighthGraduations?: Prisma.GraduationOrderByRelationAggregateInput
}

export type UploadWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UploadWhereInput | Prisma.UploadWhereInput[]
  OR?: Prisma.UploadWhereInput[]
  NOT?: Prisma.UploadWhereInput | Prisma.UploadWhereInput[]
  userId?: Prisma.StringFilter<"Upload"> | string
  subscriptionId?: Prisma.StringFilter<"Upload"> | string
  classId?: Prisma.StringFilter<"Upload"> | string
  slotIndex?: Prisma.IntFilter<"Upload"> | number
  imageUrl?: Prisma.StringFilter<"Upload"> | string
  feedbackText?: Prisma.StringNullableFilter<"Upload"> | string | null
  tasksText?: Prisma.StringNullableFilter<"Upload"> | string | null
  aiFeedbackText?: Prisma.StringNullableFilter<"Upload"> | string | null
  isHidden?: Prisma.BoolFilter<"Upload"> | boolean
  isExplicitFlag?: Prisma.BoolFilter<"Upload"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Upload"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Upload"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  subscription?: Prisma.XOR<Prisma.SubscriptionScalarRelationFilter, Prisma.SubscriptionWhereInput>
  class?: Prisma.XOR<Prisma.ClassScalarRelationFilter, Prisma.ClassWhereInput>
  eighthGraduations?: Prisma.GraduationListRelationFilter
}, "id">

export type UploadOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  slotIndex?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  feedbackText?: Prisma.SortOrderInput | Prisma.SortOrder
  tasksText?: Prisma.SortOrderInput | Prisma.SortOrder
  aiFeedbackText?: Prisma.SortOrderInput | Prisma.SortOrder
  isHidden?: Prisma.SortOrder
  isExplicitFlag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UploadCountOrderByAggregateInput
  _avg?: Prisma.UploadAvgOrderByAggregateInput
  _max?: Prisma.UploadMaxOrderByAggregateInput
  _min?: Prisma.UploadMinOrderByAggregateInput
  _sum?: Prisma.UploadSumOrderByAggregateInput
}

export type UploadScalarWhereWithAggregatesInput = {
  AND?: Prisma.UploadScalarWhereWithAggregatesInput | Prisma.UploadScalarWhereWithAggregatesInput[]
  OR?: Prisma.UploadScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UploadScalarWhereWithAggregatesInput | Prisma.UploadScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Upload"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Upload"> | string
  subscriptionId?: Prisma.StringWithAggregatesFilter<"Upload"> | string
  classId?: Prisma.StringWithAggregatesFilter<"Upload"> | string
  slotIndex?: Prisma.IntWithAggregatesFilter<"Upload"> | number
  imageUrl?: Prisma.StringWithAggregatesFilter<"Upload"> | string
  feedbackText?: Prisma.StringNullableWithAggregatesFilter<"Upload"> | string | null
  tasksText?: Prisma.StringNullableWithAggregatesFilter<"Upload"> | string | null
  aiFeedbackText?: Prisma.StringNullableWithAggregatesFilter<"Upload"> | string | null
  isHidden?: Prisma.BoolWithAggregatesFilter<"Upload"> | boolean
  isExplicitFlag?: Prisma.BoolWithAggregatesFilter<"Upload"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Upload"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Upload"> | Date | string
}

export type UploadCreateInput = {
  id?: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutUploadsInput
  subscription: Prisma.SubscriptionCreateNestedOneWithoutUploadsInput
  class: Prisma.ClassCreateNestedOneWithoutUploadsInput
  eighthGraduations?: Prisma.GraduationCreateNestedManyWithoutEighthUploadInput
}

export type UploadUncheckedCreateInput = {
  id?: string
  userId: string
  subscriptionId: string
  classId: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  eighthGraduations?: Prisma.GraduationUncheckedCreateNestedManyWithoutEighthUploadInput
}

export type UploadUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutUploadsNestedInput
  subscription?: Prisma.SubscriptionUpdateOneRequiredWithoutUploadsNestedInput
  class?: Prisma.ClassUpdateOneRequiredWithoutUploadsNestedInput
  eighthGraduations?: Prisma.GraduationUpdateManyWithoutEighthUploadNestedInput
}

export type UploadUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eighthGraduations?: Prisma.GraduationUncheckedUpdateManyWithoutEighthUploadNestedInput
}

export type UploadCreateManyInput = {
  id?: string
  userId: string
  subscriptionId: string
  classId: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UploadUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UploadUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UploadListRelationFilter = {
  every?: Prisma.UploadWhereInput
  some?: Prisma.UploadWhereInput
  none?: Prisma.UploadWhereInput
}

export type UploadOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UploadCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  slotIndex?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  feedbackText?: Prisma.SortOrder
  tasksText?: Prisma.SortOrder
  aiFeedbackText?: Prisma.SortOrder
  isHidden?: Prisma.SortOrder
  isExplicitFlag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UploadAvgOrderByAggregateInput = {
  slotIndex?: Prisma.SortOrder
}

export type UploadMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  slotIndex?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  feedbackText?: Prisma.SortOrder
  tasksText?: Prisma.SortOrder
  aiFeedbackText?: Prisma.SortOrder
  isHidden?: Prisma.SortOrder
  isExplicitFlag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UploadMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  subscriptionId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  slotIndex?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  feedbackText?: Prisma.SortOrder
  tasksText?: Prisma.SortOrder
  aiFeedbackText?: Prisma.SortOrder
  isHidden?: Prisma.SortOrder
  isExplicitFlag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UploadSumOrderByAggregateInput = {
  slotIndex?: Prisma.SortOrder
}

export type UploadNullableScalarRelationFilter = {
  is?: Prisma.UploadWhereInput | null
  isNot?: Prisma.UploadWhereInput | null
}

export type UploadCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutUserInput, Prisma.UploadUncheckedCreateWithoutUserInput> | Prisma.UploadCreateWithoutUserInput[] | Prisma.UploadUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutUserInput | Prisma.UploadCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UploadCreateManyUserInputEnvelope
  connect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
}

export type UploadUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutUserInput, Prisma.UploadUncheckedCreateWithoutUserInput> | Prisma.UploadCreateWithoutUserInput[] | Prisma.UploadUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutUserInput | Prisma.UploadCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UploadCreateManyUserInputEnvelope
  connect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
}

export type UploadUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutUserInput, Prisma.UploadUncheckedCreateWithoutUserInput> | Prisma.UploadCreateWithoutUserInput[] | Prisma.UploadUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutUserInput | Prisma.UploadCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UploadUpsertWithWhereUniqueWithoutUserInput | Prisma.UploadUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UploadCreateManyUserInputEnvelope
  set?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  disconnect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  delete?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  connect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  update?: Prisma.UploadUpdateWithWhereUniqueWithoutUserInput | Prisma.UploadUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UploadUpdateManyWithWhereWithoutUserInput | Prisma.UploadUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UploadScalarWhereInput | Prisma.UploadScalarWhereInput[]
}

export type UploadUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutUserInput, Prisma.UploadUncheckedCreateWithoutUserInput> | Prisma.UploadCreateWithoutUserInput[] | Prisma.UploadUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutUserInput | Prisma.UploadCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UploadUpsertWithWhereUniqueWithoutUserInput | Prisma.UploadUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UploadCreateManyUserInputEnvelope
  set?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  disconnect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  delete?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  connect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  update?: Prisma.UploadUpdateWithWhereUniqueWithoutUserInput | Prisma.UploadUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UploadUpdateManyWithWhereWithoutUserInput | Prisma.UploadUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UploadScalarWhereInput | Prisma.UploadScalarWhereInput[]
}

export type UploadCreateNestedManyWithoutClassInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutClassInput, Prisma.UploadUncheckedCreateWithoutClassInput> | Prisma.UploadCreateWithoutClassInput[] | Prisma.UploadUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutClassInput | Prisma.UploadCreateOrConnectWithoutClassInput[]
  createMany?: Prisma.UploadCreateManyClassInputEnvelope
  connect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
}

export type UploadUncheckedCreateNestedManyWithoutClassInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutClassInput, Prisma.UploadUncheckedCreateWithoutClassInput> | Prisma.UploadCreateWithoutClassInput[] | Prisma.UploadUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutClassInput | Prisma.UploadCreateOrConnectWithoutClassInput[]
  createMany?: Prisma.UploadCreateManyClassInputEnvelope
  connect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
}

export type UploadUpdateManyWithoutClassNestedInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutClassInput, Prisma.UploadUncheckedCreateWithoutClassInput> | Prisma.UploadCreateWithoutClassInput[] | Prisma.UploadUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutClassInput | Prisma.UploadCreateOrConnectWithoutClassInput[]
  upsert?: Prisma.UploadUpsertWithWhereUniqueWithoutClassInput | Prisma.UploadUpsertWithWhereUniqueWithoutClassInput[]
  createMany?: Prisma.UploadCreateManyClassInputEnvelope
  set?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  disconnect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  delete?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  connect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  update?: Prisma.UploadUpdateWithWhereUniqueWithoutClassInput | Prisma.UploadUpdateWithWhereUniqueWithoutClassInput[]
  updateMany?: Prisma.UploadUpdateManyWithWhereWithoutClassInput | Prisma.UploadUpdateManyWithWhereWithoutClassInput[]
  deleteMany?: Prisma.UploadScalarWhereInput | Prisma.UploadScalarWhereInput[]
}

export type UploadUncheckedUpdateManyWithoutClassNestedInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutClassInput, Prisma.UploadUncheckedCreateWithoutClassInput> | Prisma.UploadCreateWithoutClassInput[] | Prisma.UploadUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutClassInput | Prisma.UploadCreateOrConnectWithoutClassInput[]
  upsert?: Prisma.UploadUpsertWithWhereUniqueWithoutClassInput | Prisma.UploadUpsertWithWhereUniqueWithoutClassInput[]
  createMany?: Prisma.UploadCreateManyClassInputEnvelope
  set?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  disconnect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  delete?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  connect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  update?: Prisma.UploadUpdateWithWhereUniqueWithoutClassInput | Prisma.UploadUpdateWithWhereUniqueWithoutClassInput[]
  updateMany?: Prisma.UploadUpdateManyWithWhereWithoutClassInput | Prisma.UploadUpdateManyWithWhereWithoutClassInput[]
  deleteMany?: Prisma.UploadScalarWhereInput | Prisma.UploadScalarWhereInput[]
}

export type UploadCreateNestedManyWithoutSubscriptionInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutSubscriptionInput, Prisma.UploadUncheckedCreateWithoutSubscriptionInput> | Prisma.UploadCreateWithoutSubscriptionInput[] | Prisma.UploadUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutSubscriptionInput | Prisma.UploadCreateOrConnectWithoutSubscriptionInput[]
  createMany?: Prisma.UploadCreateManySubscriptionInputEnvelope
  connect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
}

export type UploadUncheckedCreateNestedManyWithoutSubscriptionInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutSubscriptionInput, Prisma.UploadUncheckedCreateWithoutSubscriptionInput> | Prisma.UploadCreateWithoutSubscriptionInput[] | Prisma.UploadUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutSubscriptionInput | Prisma.UploadCreateOrConnectWithoutSubscriptionInput[]
  createMany?: Prisma.UploadCreateManySubscriptionInputEnvelope
  connect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
}

export type UploadUpdateManyWithoutSubscriptionNestedInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutSubscriptionInput, Prisma.UploadUncheckedCreateWithoutSubscriptionInput> | Prisma.UploadCreateWithoutSubscriptionInput[] | Prisma.UploadUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutSubscriptionInput | Prisma.UploadCreateOrConnectWithoutSubscriptionInput[]
  upsert?: Prisma.UploadUpsertWithWhereUniqueWithoutSubscriptionInput | Prisma.UploadUpsertWithWhereUniqueWithoutSubscriptionInput[]
  createMany?: Prisma.UploadCreateManySubscriptionInputEnvelope
  set?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  disconnect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  delete?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  connect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  update?: Prisma.UploadUpdateWithWhereUniqueWithoutSubscriptionInput | Prisma.UploadUpdateWithWhereUniqueWithoutSubscriptionInput[]
  updateMany?: Prisma.UploadUpdateManyWithWhereWithoutSubscriptionInput | Prisma.UploadUpdateManyWithWhereWithoutSubscriptionInput[]
  deleteMany?: Prisma.UploadScalarWhereInput | Prisma.UploadScalarWhereInput[]
}

export type UploadUncheckedUpdateManyWithoutSubscriptionNestedInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutSubscriptionInput, Prisma.UploadUncheckedCreateWithoutSubscriptionInput> | Prisma.UploadCreateWithoutSubscriptionInput[] | Prisma.UploadUncheckedCreateWithoutSubscriptionInput[]
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutSubscriptionInput | Prisma.UploadCreateOrConnectWithoutSubscriptionInput[]
  upsert?: Prisma.UploadUpsertWithWhereUniqueWithoutSubscriptionInput | Prisma.UploadUpsertWithWhereUniqueWithoutSubscriptionInput[]
  createMany?: Prisma.UploadCreateManySubscriptionInputEnvelope
  set?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  disconnect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  delete?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  connect?: Prisma.UploadWhereUniqueInput | Prisma.UploadWhereUniqueInput[]
  update?: Prisma.UploadUpdateWithWhereUniqueWithoutSubscriptionInput | Prisma.UploadUpdateWithWhereUniqueWithoutSubscriptionInput[]
  updateMany?: Prisma.UploadUpdateManyWithWhereWithoutSubscriptionInput | Prisma.UploadUpdateManyWithWhereWithoutSubscriptionInput[]
  deleteMany?: Prisma.UploadScalarWhereInput | Prisma.UploadScalarWhereInput[]
}

export type UploadCreateNestedOneWithoutEighthGraduationsInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutEighthGraduationsInput, Prisma.UploadUncheckedCreateWithoutEighthGraduationsInput>
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutEighthGraduationsInput
  connect?: Prisma.UploadWhereUniqueInput
}

export type UploadUpdateOneWithoutEighthGraduationsNestedInput = {
  create?: Prisma.XOR<Prisma.UploadCreateWithoutEighthGraduationsInput, Prisma.UploadUncheckedCreateWithoutEighthGraduationsInput>
  connectOrCreate?: Prisma.UploadCreateOrConnectWithoutEighthGraduationsInput
  upsert?: Prisma.UploadUpsertWithoutEighthGraduationsInput
  disconnect?: Prisma.UploadWhereInput | boolean
  delete?: Prisma.UploadWhereInput | boolean
  connect?: Prisma.UploadWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UploadUpdateToOneWithWhereWithoutEighthGraduationsInput, Prisma.UploadUpdateWithoutEighthGraduationsInput>, Prisma.UploadUncheckedUpdateWithoutEighthGraduationsInput>
}

export type UploadCreateWithoutUserInput = {
  id?: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  subscription: Prisma.SubscriptionCreateNestedOneWithoutUploadsInput
  class: Prisma.ClassCreateNestedOneWithoutUploadsInput
  eighthGraduations?: Prisma.GraduationCreateNestedManyWithoutEighthUploadInput
}

export type UploadUncheckedCreateWithoutUserInput = {
  id?: string
  subscriptionId: string
  classId: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  eighthGraduations?: Prisma.GraduationUncheckedCreateNestedManyWithoutEighthUploadInput
}

export type UploadCreateOrConnectWithoutUserInput = {
  where: Prisma.UploadWhereUniqueInput
  create: Prisma.XOR<Prisma.UploadCreateWithoutUserInput, Prisma.UploadUncheckedCreateWithoutUserInput>
}

export type UploadCreateManyUserInputEnvelope = {
  data: Prisma.UploadCreateManyUserInput | Prisma.UploadCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UploadUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UploadWhereUniqueInput
  update: Prisma.XOR<Prisma.UploadUpdateWithoutUserInput, Prisma.UploadUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UploadCreateWithoutUserInput, Prisma.UploadUncheckedCreateWithoutUserInput>
}

export type UploadUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UploadWhereUniqueInput
  data: Prisma.XOR<Prisma.UploadUpdateWithoutUserInput, Prisma.UploadUncheckedUpdateWithoutUserInput>
}

export type UploadUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UploadScalarWhereInput
  data: Prisma.XOR<Prisma.UploadUpdateManyMutationInput, Prisma.UploadUncheckedUpdateManyWithoutUserInput>
}

export type UploadScalarWhereInput = {
  AND?: Prisma.UploadScalarWhereInput | Prisma.UploadScalarWhereInput[]
  OR?: Prisma.UploadScalarWhereInput[]
  NOT?: Prisma.UploadScalarWhereInput | Prisma.UploadScalarWhereInput[]
  id?: Prisma.StringFilter<"Upload"> | string
  userId?: Prisma.StringFilter<"Upload"> | string
  subscriptionId?: Prisma.StringFilter<"Upload"> | string
  classId?: Prisma.StringFilter<"Upload"> | string
  slotIndex?: Prisma.IntFilter<"Upload"> | number
  imageUrl?: Prisma.StringFilter<"Upload"> | string
  feedbackText?: Prisma.StringNullableFilter<"Upload"> | string | null
  tasksText?: Prisma.StringNullableFilter<"Upload"> | string | null
  aiFeedbackText?: Prisma.StringNullableFilter<"Upload"> | string | null
  isHidden?: Prisma.BoolFilter<"Upload"> | boolean
  isExplicitFlag?: Prisma.BoolFilter<"Upload"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Upload"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Upload"> | Date | string
}

export type UploadCreateWithoutClassInput = {
  id?: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutUploadsInput
  subscription: Prisma.SubscriptionCreateNestedOneWithoutUploadsInput
  eighthGraduations?: Prisma.GraduationCreateNestedManyWithoutEighthUploadInput
}

export type UploadUncheckedCreateWithoutClassInput = {
  id?: string
  userId: string
  subscriptionId: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  eighthGraduations?: Prisma.GraduationUncheckedCreateNestedManyWithoutEighthUploadInput
}

export type UploadCreateOrConnectWithoutClassInput = {
  where: Prisma.UploadWhereUniqueInput
  create: Prisma.XOR<Prisma.UploadCreateWithoutClassInput, Prisma.UploadUncheckedCreateWithoutClassInput>
}

export type UploadCreateManyClassInputEnvelope = {
  data: Prisma.UploadCreateManyClassInput | Prisma.UploadCreateManyClassInput[]
  skipDuplicates?: boolean
}

export type UploadUpsertWithWhereUniqueWithoutClassInput = {
  where: Prisma.UploadWhereUniqueInput
  update: Prisma.XOR<Prisma.UploadUpdateWithoutClassInput, Prisma.UploadUncheckedUpdateWithoutClassInput>
  create: Prisma.XOR<Prisma.UploadCreateWithoutClassInput, Prisma.UploadUncheckedCreateWithoutClassInput>
}

export type UploadUpdateWithWhereUniqueWithoutClassInput = {
  where: Prisma.UploadWhereUniqueInput
  data: Prisma.XOR<Prisma.UploadUpdateWithoutClassInput, Prisma.UploadUncheckedUpdateWithoutClassInput>
}

export type UploadUpdateManyWithWhereWithoutClassInput = {
  where: Prisma.UploadScalarWhereInput
  data: Prisma.XOR<Prisma.UploadUpdateManyMutationInput, Prisma.UploadUncheckedUpdateManyWithoutClassInput>
}

export type UploadCreateWithoutSubscriptionInput = {
  id?: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutUploadsInput
  class: Prisma.ClassCreateNestedOneWithoutUploadsInput
  eighthGraduations?: Prisma.GraduationCreateNestedManyWithoutEighthUploadInput
}

export type UploadUncheckedCreateWithoutSubscriptionInput = {
  id?: string
  userId: string
  classId: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  eighthGraduations?: Prisma.GraduationUncheckedCreateNestedManyWithoutEighthUploadInput
}

export type UploadCreateOrConnectWithoutSubscriptionInput = {
  where: Prisma.UploadWhereUniqueInput
  create: Prisma.XOR<Prisma.UploadCreateWithoutSubscriptionInput, Prisma.UploadUncheckedCreateWithoutSubscriptionInput>
}

export type UploadCreateManySubscriptionInputEnvelope = {
  data: Prisma.UploadCreateManySubscriptionInput | Prisma.UploadCreateManySubscriptionInput[]
  skipDuplicates?: boolean
}

export type UploadUpsertWithWhereUniqueWithoutSubscriptionInput = {
  where: Prisma.UploadWhereUniqueInput
  update: Prisma.XOR<Prisma.UploadUpdateWithoutSubscriptionInput, Prisma.UploadUncheckedUpdateWithoutSubscriptionInput>
  create: Prisma.XOR<Prisma.UploadCreateWithoutSubscriptionInput, Prisma.UploadUncheckedCreateWithoutSubscriptionInput>
}

export type UploadUpdateWithWhereUniqueWithoutSubscriptionInput = {
  where: Prisma.UploadWhereUniqueInput
  data: Prisma.XOR<Prisma.UploadUpdateWithoutSubscriptionInput, Prisma.UploadUncheckedUpdateWithoutSubscriptionInput>
}

export type UploadUpdateManyWithWhereWithoutSubscriptionInput = {
  where: Prisma.UploadScalarWhereInput
  data: Prisma.XOR<Prisma.UploadUpdateManyMutationInput, Prisma.UploadUncheckedUpdateManyWithoutSubscriptionInput>
}

export type UploadCreateWithoutEighthGraduationsInput = {
  id?: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutUploadsInput
  subscription: Prisma.SubscriptionCreateNestedOneWithoutUploadsInput
  class: Prisma.ClassCreateNestedOneWithoutUploadsInput
}

export type UploadUncheckedCreateWithoutEighthGraduationsInput = {
  id?: string
  userId: string
  subscriptionId: string
  classId: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UploadCreateOrConnectWithoutEighthGraduationsInput = {
  where: Prisma.UploadWhereUniqueInput
  create: Prisma.XOR<Prisma.UploadCreateWithoutEighthGraduationsInput, Prisma.UploadUncheckedCreateWithoutEighthGraduationsInput>
}

export type UploadUpsertWithoutEighthGraduationsInput = {
  update: Prisma.XOR<Prisma.UploadUpdateWithoutEighthGraduationsInput, Prisma.UploadUncheckedUpdateWithoutEighthGraduationsInput>
  create: Prisma.XOR<Prisma.UploadCreateWithoutEighthGraduationsInput, Prisma.UploadUncheckedCreateWithoutEighthGraduationsInput>
  where?: Prisma.UploadWhereInput
}

export type UploadUpdateToOneWithWhereWithoutEighthGraduationsInput = {
  where?: Prisma.UploadWhereInput
  data: Prisma.XOR<Prisma.UploadUpdateWithoutEighthGraduationsInput, Prisma.UploadUncheckedUpdateWithoutEighthGraduationsInput>
}

export type UploadUpdateWithoutEighthGraduationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutUploadsNestedInput
  subscription?: Prisma.SubscriptionUpdateOneRequiredWithoutUploadsNestedInput
  class?: Prisma.ClassUpdateOneRequiredWithoutUploadsNestedInput
}

export type UploadUncheckedUpdateWithoutEighthGraduationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UploadCreateManyUserInput = {
  id?: string
  subscriptionId: string
  classId: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UploadUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscription?: Prisma.SubscriptionUpdateOneRequiredWithoutUploadsNestedInput
  class?: Prisma.ClassUpdateOneRequiredWithoutUploadsNestedInput
  eighthGraduations?: Prisma.GraduationUpdateManyWithoutEighthUploadNestedInput
}

export type UploadUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eighthGraduations?: Prisma.GraduationUncheckedUpdateManyWithoutEighthUploadNestedInput
}

export type UploadUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UploadCreateManyClassInput = {
  id?: string
  userId: string
  subscriptionId: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UploadUpdateWithoutClassInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutUploadsNestedInput
  subscription?: Prisma.SubscriptionUpdateOneRequiredWithoutUploadsNestedInput
  eighthGraduations?: Prisma.GraduationUpdateManyWithoutEighthUploadNestedInput
}

export type UploadUncheckedUpdateWithoutClassInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eighthGraduations?: Prisma.GraduationUncheckedUpdateManyWithoutEighthUploadNestedInput
}

export type UploadUncheckedUpdateManyWithoutClassInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  subscriptionId?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UploadCreateManySubscriptionInput = {
  id?: string
  userId: string
  classId: string
  slotIndex: number
  imageUrl: string
  feedbackText?: string | null
  tasksText?: string | null
  aiFeedbackText?: string | null
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UploadUpdateWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutUploadsNestedInput
  class?: Prisma.ClassUpdateOneRequiredWithoutUploadsNestedInput
  eighthGraduations?: Prisma.GraduationUpdateManyWithoutEighthUploadNestedInput
}

export type UploadUncheckedUpdateWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eighthGraduations?: Prisma.GraduationUncheckedUpdateManyWithoutEighthUploadNestedInput
}

export type UploadUncheckedUpdateManyWithoutSubscriptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  classId?: Prisma.StringFieldUpdateOperationsInput | string
  slotIndex?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  feedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasksText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aiFeedbackText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isHidden?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isExplicitFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type UploadCountOutputType
 */

export type UploadCountOutputType = {
  eighthGraduations: number
}

export type UploadCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  eighthGraduations?: boolean | UploadCountOutputTypeCountEighthGraduationsArgs
}

/**
 * UploadCountOutputType without action
 */
export type UploadCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadCountOutputType
   */
  select?: Prisma.UploadCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UploadCountOutputType without action
 */
export type UploadCountOutputTypeCountEighthGraduationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GraduationWhereInput
}


export type UploadSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  subscriptionId?: boolean
  classId?: boolean
  slotIndex?: boolean
  imageUrl?: boolean
  feedbackText?: boolean
  tasksText?: boolean
  aiFeedbackText?: boolean
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  class?: boolean | Prisma.ClassDefaultArgs<ExtArgs>
  eighthGraduations?: boolean | Prisma.Upload$eighthGraduationsArgs<ExtArgs>
  _count?: boolean | Prisma.UploadCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["upload"]>

export type UploadSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  subscriptionId?: boolean
  classId?: boolean
  slotIndex?: boolean
  imageUrl?: boolean
  feedbackText?: boolean
  tasksText?: boolean
  aiFeedbackText?: boolean
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  class?: boolean | Prisma.ClassDefaultArgs<ExtArgs>
}, ExtArgs["result"]["upload"]>

export type UploadSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  subscriptionId?: boolean
  classId?: boolean
  slotIndex?: boolean
  imageUrl?: boolean
  feedbackText?: boolean
  tasksText?: boolean
  aiFeedbackText?: boolean
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  class?: boolean | Prisma.ClassDefaultArgs<ExtArgs>
}, ExtArgs["result"]["upload"]>

export type UploadSelectScalar = {
  id?: boolean
  userId?: boolean
  subscriptionId?: boolean
  classId?: boolean
  slotIndex?: boolean
  imageUrl?: boolean
  feedbackText?: boolean
  tasksText?: boolean
  aiFeedbackText?: boolean
  isHidden?: boolean
  isExplicitFlag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UploadOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "subscriptionId" | "classId" | "slotIndex" | "imageUrl" | "feedbackText" | "tasksText" | "aiFeedbackText" | "isHidden" | "isExplicitFlag" | "createdAt" | "updatedAt", ExtArgs["result"]["upload"]>
export type UploadInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  class?: boolean | Prisma.ClassDefaultArgs<ExtArgs>
  eighthGraduations?: boolean | Prisma.Upload$eighthGraduationsArgs<ExtArgs>
  _count?: boolean | Prisma.UploadCountOutputTypeDefaultArgs<ExtArgs>
}
export type UploadIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  class?: boolean | Prisma.ClassDefaultArgs<ExtArgs>
}
export type UploadIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  subscription?: boolean | Prisma.SubscriptionDefaultArgs<ExtArgs>
  class?: boolean | Prisma.ClassDefaultArgs<ExtArgs>
}

export type $UploadPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Upload"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    subscription: Prisma.$SubscriptionPayload<ExtArgs>
    class: Prisma.$ClassPayload<ExtArgs>
    eighthGraduations: Prisma.$GraduationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    subscriptionId: string
    classId: string
    slotIndex: number
    imageUrl: string
    feedbackText: string | null
    tasksText: string | null
    aiFeedbackText: string | null
    isHidden: boolean
    isExplicitFlag: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["upload"]>
  composites: {}
}

export type UploadGetPayload<S extends boolean | null | undefined | UploadDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UploadPayload, S>

export type UploadCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UploadFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UploadCountAggregateInputType | true
  }

export interface UploadDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Upload'], meta: { name: 'Upload' } }
  /**
   * Find zero or one Upload that matches the filter.
   * @param {UploadFindUniqueArgs} args - Arguments to find a Upload
   * @example
   * // Get one Upload
   * const upload = await prisma.upload.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UploadFindUniqueArgs>(args: Prisma.SelectSubset<T, UploadFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UploadClient<runtime.Types.Result.GetResult<Prisma.$UploadPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Upload that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UploadFindUniqueOrThrowArgs} args - Arguments to find a Upload
   * @example
   * // Get one Upload
   * const upload = await prisma.upload.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UploadFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UploadFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UploadClient<runtime.Types.Result.GetResult<Prisma.$UploadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Upload that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadFindFirstArgs} args - Arguments to find a Upload
   * @example
   * // Get one Upload
   * const upload = await prisma.upload.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UploadFindFirstArgs>(args?: Prisma.SelectSubset<T, UploadFindFirstArgs<ExtArgs>>): Prisma.Prisma__UploadClient<runtime.Types.Result.GetResult<Prisma.$UploadPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Upload that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadFindFirstOrThrowArgs} args - Arguments to find a Upload
   * @example
   * // Get one Upload
   * const upload = await prisma.upload.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UploadFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UploadFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UploadClient<runtime.Types.Result.GetResult<Prisma.$UploadPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Uploads that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Uploads
   * const uploads = await prisma.upload.findMany()
   * 
   * // Get first 10 Uploads
   * const uploads = await prisma.upload.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const uploadWithIdOnly = await prisma.upload.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UploadFindManyArgs>(args?: Prisma.SelectSubset<T, UploadFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UploadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Upload.
   * @param {UploadCreateArgs} args - Arguments to create a Upload.
   * @example
   * // Create one Upload
   * const Upload = await prisma.upload.create({
   *   data: {
   *     // ... data to create a Upload
   *   }
   * })
   * 
   */
  create<T extends UploadCreateArgs>(args: Prisma.SelectSubset<T, UploadCreateArgs<ExtArgs>>): Prisma.Prisma__UploadClient<runtime.Types.Result.GetResult<Prisma.$UploadPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Uploads.
   * @param {UploadCreateManyArgs} args - Arguments to create many Uploads.
   * @example
   * // Create many Uploads
   * const upload = await prisma.upload.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UploadCreateManyArgs>(args?: Prisma.SelectSubset<T, UploadCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Uploads and returns the data saved in the database.
   * @param {UploadCreateManyAndReturnArgs} args - Arguments to create many Uploads.
   * @example
   * // Create many Uploads
   * const upload = await prisma.upload.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Uploads and only return the `id`
   * const uploadWithIdOnly = await prisma.upload.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UploadCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UploadCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UploadPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Upload.
   * @param {UploadDeleteArgs} args - Arguments to delete one Upload.
   * @example
   * // Delete one Upload
   * const Upload = await prisma.upload.delete({
   *   where: {
   *     // ... filter to delete one Upload
   *   }
   * })
   * 
   */
  delete<T extends UploadDeleteArgs>(args: Prisma.SelectSubset<T, UploadDeleteArgs<ExtArgs>>): Prisma.Prisma__UploadClient<runtime.Types.Result.GetResult<Prisma.$UploadPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Upload.
   * @param {UploadUpdateArgs} args - Arguments to update one Upload.
   * @example
   * // Update one Upload
   * const upload = await prisma.upload.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UploadUpdateArgs>(args: Prisma.SelectSubset<T, UploadUpdateArgs<ExtArgs>>): Prisma.Prisma__UploadClient<runtime.Types.Result.GetResult<Prisma.$UploadPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Uploads.
   * @param {UploadDeleteManyArgs} args - Arguments to filter Uploads to delete.
   * @example
   * // Delete a few Uploads
   * const { count } = await prisma.upload.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UploadDeleteManyArgs>(args?: Prisma.SelectSubset<T, UploadDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Uploads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Uploads
   * const upload = await prisma.upload.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UploadUpdateManyArgs>(args: Prisma.SelectSubset<T, UploadUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Uploads and returns the data updated in the database.
   * @param {UploadUpdateManyAndReturnArgs} args - Arguments to update many Uploads.
   * @example
   * // Update many Uploads
   * const upload = await prisma.upload.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Uploads and only return the `id`
   * const uploadWithIdOnly = await prisma.upload.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UploadUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UploadUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UploadPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Upload.
   * @param {UploadUpsertArgs} args - Arguments to update or create a Upload.
   * @example
   * // Update or create a Upload
   * const upload = await prisma.upload.upsert({
   *   create: {
   *     // ... data to create a Upload
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Upload we want to update
   *   }
   * })
   */
  upsert<T extends UploadUpsertArgs>(args: Prisma.SelectSubset<T, UploadUpsertArgs<ExtArgs>>): Prisma.Prisma__UploadClient<runtime.Types.Result.GetResult<Prisma.$UploadPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Uploads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadCountArgs} args - Arguments to filter Uploads to count.
   * @example
   * // Count the number of Uploads
   * const count = await prisma.upload.count({
   *   where: {
   *     // ... the filter for the Uploads we want to count
   *   }
   * })
  **/
  count<T extends UploadCountArgs>(
    args?: Prisma.Subset<T, UploadCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UploadCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Upload.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UploadAggregateArgs>(args: Prisma.Subset<T, UploadAggregateArgs>): Prisma.PrismaPromise<GetUploadAggregateType<T>>

  /**
   * Group by Upload.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UploadGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UploadGroupByArgs['orderBy'] }
      : { orderBy?: UploadGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UploadGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUploadGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Upload model
 */
readonly fields: UploadFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Upload.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UploadClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  subscription<T extends Prisma.SubscriptionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubscriptionDefaultArgs<ExtArgs>>): Prisma.Prisma__SubscriptionClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  class<T extends Prisma.ClassDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClassDefaultArgs<ExtArgs>>): Prisma.Prisma__ClassClient<runtime.Types.Result.GetResult<Prisma.$ClassPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  eighthGraduations<T extends Prisma.Upload$eighthGraduationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Upload$eighthGraduationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GraduationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Upload model
 */
export interface UploadFieldRefs {
  readonly id: Prisma.FieldRef<"Upload", 'String'>
  readonly userId: Prisma.FieldRef<"Upload", 'String'>
  readonly subscriptionId: Prisma.FieldRef<"Upload", 'String'>
  readonly classId: Prisma.FieldRef<"Upload", 'String'>
  readonly slotIndex: Prisma.FieldRef<"Upload", 'Int'>
  readonly imageUrl: Prisma.FieldRef<"Upload", 'String'>
  readonly feedbackText: Prisma.FieldRef<"Upload", 'String'>
  readonly tasksText: Prisma.FieldRef<"Upload", 'String'>
  readonly aiFeedbackText: Prisma.FieldRef<"Upload", 'String'>
  readonly isHidden: Prisma.FieldRef<"Upload", 'Boolean'>
  readonly isExplicitFlag: Prisma.FieldRef<"Upload", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Upload", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Upload", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Upload findUnique
 */
export type UploadFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadInclude<ExtArgs> | null
  /**
   * Filter, which Upload to fetch.
   */
  where: Prisma.UploadWhereUniqueInput
}

/**
 * Upload findUniqueOrThrow
 */
export type UploadFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadInclude<ExtArgs> | null
  /**
   * Filter, which Upload to fetch.
   */
  where: Prisma.UploadWhereUniqueInput
}

/**
 * Upload findFirst
 */
export type UploadFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadInclude<ExtArgs> | null
  /**
   * Filter, which Upload to fetch.
   */
  where?: Prisma.UploadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Uploads to fetch.
   */
  orderBy?: Prisma.UploadOrderByWithRelationInput | Prisma.UploadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Uploads.
   */
  cursor?: Prisma.UploadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Uploads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Uploads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Uploads.
   */
  distinct?: Prisma.UploadScalarFieldEnum | Prisma.UploadScalarFieldEnum[]
}

/**
 * Upload findFirstOrThrow
 */
export type UploadFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadInclude<ExtArgs> | null
  /**
   * Filter, which Upload to fetch.
   */
  where?: Prisma.UploadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Uploads to fetch.
   */
  orderBy?: Prisma.UploadOrderByWithRelationInput | Prisma.UploadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Uploads.
   */
  cursor?: Prisma.UploadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Uploads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Uploads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Uploads.
   */
  distinct?: Prisma.UploadScalarFieldEnum | Prisma.UploadScalarFieldEnum[]
}

/**
 * Upload findMany
 */
export type UploadFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadInclude<ExtArgs> | null
  /**
   * Filter, which Uploads to fetch.
   */
  where?: Prisma.UploadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Uploads to fetch.
   */
  orderBy?: Prisma.UploadOrderByWithRelationInput | Prisma.UploadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Uploads.
   */
  cursor?: Prisma.UploadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Uploads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Uploads.
   */
  skip?: number
  distinct?: Prisma.UploadScalarFieldEnum | Prisma.UploadScalarFieldEnum[]
}

/**
 * Upload create
 */
export type UploadCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadInclude<ExtArgs> | null
  /**
   * The data needed to create a Upload.
   */
  data: Prisma.XOR<Prisma.UploadCreateInput, Prisma.UploadUncheckedCreateInput>
}

/**
 * Upload createMany
 */
export type UploadCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Uploads.
   */
  data: Prisma.UploadCreateManyInput | Prisma.UploadCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Upload createManyAndReturn
 */
export type UploadCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * The data used to create many Uploads.
   */
  data: Prisma.UploadCreateManyInput | Prisma.UploadCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Upload update
 */
export type UploadUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadInclude<ExtArgs> | null
  /**
   * The data needed to update a Upload.
   */
  data: Prisma.XOR<Prisma.UploadUpdateInput, Prisma.UploadUncheckedUpdateInput>
  /**
   * Choose, which Upload to update.
   */
  where: Prisma.UploadWhereUniqueInput
}

/**
 * Upload updateMany
 */
export type UploadUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Uploads.
   */
  data: Prisma.XOR<Prisma.UploadUpdateManyMutationInput, Prisma.UploadUncheckedUpdateManyInput>
  /**
   * Filter which Uploads to update
   */
  where?: Prisma.UploadWhereInput
  /**
   * Limit how many Uploads to update.
   */
  limit?: number
}

/**
 * Upload updateManyAndReturn
 */
export type UploadUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * The data used to update Uploads.
   */
  data: Prisma.XOR<Prisma.UploadUpdateManyMutationInput, Prisma.UploadUncheckedUpdateManyInput>
  /**
   * Filter which Uploads to update
   */
  where?: Prisma.UploadWhereInput
  /**
   * Limit how many Uploads to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Upload upsert
 */
export type UploadUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadInclude<ExtArgs> | null
  /**
   * The filter to search for the Upload to update in case it exists.
   */
  where: Prisma.UploadWhereUniqueInput
  /**
   * In case the Upload found by the `where` argument doesn't exist, create a new Upload with this data.
   */
  create: Prisma.XOR<Prisma.UploadCreateInput, Prisma.UploadUncheckedCreateInput>
  /**
   * In case the Upload was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UploadUpdateInput, Prisma.UploadUncheckedUpdateInput>
}

/**
 * Upload delete
 */
export type UploadDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadInclude<ExtArgs> | null
  /**
   * Filter which Upload to delete.
   */
  where: Prisma.UploadWhereUniqueInput
}

/**
 * Upload deleteMany
 */
export type UploadDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Uploads to delete
   */
  where?: Prisma.UploadWhereInput
  /**
   * Limit how many Uploads to delete.
   */
  limit?: number
}

/**
 * Upload.eighthGraduations
 */
export type Upload$eighthGraduationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graduation
   */
  select?: Prisma.GraduationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Graduation
   */
  omit?: Prisma.GraduationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraduationInclude<ExtArgs> | null
  where?: Prisma.GraduationWhereInput
  orderBy?: Prisma.GraduationOrderByWithRelationInput | Prisma.GraduationOrderByWithRelationInput[]
  cursor?: Prisma.GraduationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.GraduationScalarFieldEnum | Prisma.GraduationScalarFieldEnum[]
}

/**
 * Upload without action
 */
export type UploadDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Upload
   */
  select?: Prisma.UploadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Upload
   */
  omit?: Prisma.UploadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadInclude<ExtArgs> | null
}
